import chineseS2t from 'chinese-s2t';
import type { Lang } from '../i18n';
import { HLS_CONFIG } from '../../../config/hls.mjs';
import { streamTranslations } from './stream-copy';

const zh = {
  source: '视频来源', url: 'M3U8 播放列表地址', urlPlaceholder: 'https://example.com/video/index.m3u8',
  parse: '解析链接', settings: '下载设置', concurrency: '并发下载', retries: '失败重试次数', timeout: '请求超时（秒）',
  filename: '保存文件名', credentials: '发送源站登录 Cookie', rangeStart: '起始分片', rangeEnd: '结束分片（留空到末尾）',
  skipBadge: '自动跳过缺失分片', sourceNote: '粘贴直接的 M3U8 地址。资源请求发送到源站，视频在本地处理。',
  quality: '选择清晰度', loadQuality: '载入此清晰度', workspace: '下载任务', empty: '准备接续每一段画面',
  emptyNote: '解析链接后，在这里查看下载进度与每个分片的状态。', resume: '继续下载', pause: '暂停下载',
  downloadAndExport: '下载并导出', resumeAndExport: '继续下载并导出', exportAgain: '重新导出',
  retry: '重试跳过的分片', clear: '清除本任务缓存', ready: '已解析 {count} 个分片 · {duration}', cached: '恢复了 {count} 个缓存分片',
  liveNote: '这是直播列表：仅下载当前快照，不持续录制。', downloading: '正在下载，缺失分片将自动跳过',
  paused: '已暂停，下载成功的分片已保留', complete: '下载结束：成功 {done} · 跳过 {skipped}',
  doneLabel: '下载成功', skippedLabel: '已跳过', bytesLabel: '已缓存', durationLabel: '保留时长',
  pending: '待下载', fetching: '下载中', retrying: '重试中', done: '成功', skipped: '跳过',
  segments: '分片状态', segmentLabel: '分片 {index} · {state} · 已请求 {attempts} 次', previous: '上一页', next: '下一页',
  page: '第 {page} / {pages} 页', exportTitle: '接续与导出', exportNote: '下载完成后自动按原顺序封装时间轴，不重新编码，缺失画面会被移除。也可以在这里重新导出。',
  mp4: '导出 MP4', ts: '导出 TS', report: '下载缺失报告', cancelExport: '取消导出',
  loadCore: '正在加载本地合并引擎 {percent}%', preparing: '正在准备分片 {done} / {total}', merging: '正在接续时间轴并封装 {percent}%',
  exported: '已生成 {format} · {size}，可预览或再次保存', saveAgain: '再次保存视频', preview: '导出视频预览',
  limitations: '首次处理需加载约 {coreMiB} MiB 引擎。普通导出上限 {maxMiB} MiB；特大模式逐片写入文件，仍受单片大小和磁盘空间限制。目标站点须允许跨域访问。',
  gapNote: '已跳过 {count} 个分片（{duration}）。这些画面无法恢复，后续内容继续接上。',
  parseBusy: '正在读取播放列表…', clearDone: '本任务缓存已清除，可重新下载', noneSkipped: '没有可重试的分片',
  invalidUrl: '请输入有效的 HTTP / HTTPS 视频地址。', invalidPlaylist: '这不是有效的 HLS 播放列表，请检查链接或列表内容。',
  unsupportedPlaylist: '暂不支持带变量替换的播放列表，请使用具体的媒体列表地址。',
  unsupportedEncryption: '此视频使用 SAMPLE-AES、DRM 或其他不支持的加密方式。支持标准 AES-128。',
  externalAudio: '此清晰度使用独立音轨，暂不支持合并。请选择内含音轨的媒体列表。',
  networkError: '请求失败：检查网络、链接有效期和源站的跨域（CORS）设置。', timeoutError: '请求超时，请增加超时或检查网络。',
  cacheError: '无法读写本地缓存，请检查浏览器存储权限与可用空间。已有缓存会保留。',
  invalidKey: 'AES 密钥不是有效的 16 字节数据，请检查权限或源站响应。任务已暂停。',
  decryptError: 'AES 解密失败，请检查密钥或加密格式。任务已暂停。',
  coreLoadError: '合并引擎加载失败，请刷新或检查站点资源。视频缓存已保留。',
  remuxError: '重新封装失败，可能存在损坏分片、编码变化或格式不兼容。请检查报告，或改用 TS。缓存已保留。',
  remuxTimeout: '合并超时，可缩小分片范围后重试。缓存已保留。',
  exportCancelled: '已取消导出，视频缓存已保留。', noSegments: '没有下载成功的分片，暂时无法导出。',
  exportTooLarge: '选中媒体超过 {maxMiB} MiB，无法在浏览器中可靠合并。请设置分片范围分批处理。缓存已保留。',
  invalidRange: '源站返回了不正确的字节范围。', emptySegment: '源站返回空分片。', invalidMedia: '返回内容不是有效的媒体分片。',
  playlistGap: '播放列表标记为缺失', httpError: '源站请求失败。', rangeError: '分片范围无效，请输入列表中的分片编号。',
  storageNote: '缓存仅保存在此浏览器；刷新后重新解析相同列表即可恢复。', speed: '{speed}/s',
  attribution: '参考项目', probeSkipped: '检测到 {count} 个损坏分片，已从导出中跳过并记录到报告。',
};

const en: typeof zh = {
  source: 'Video source', url: 'M3U8 playlist URL', urlPlaceholder: 'https://example.com/video/index.m3u8',
  parse: 'Parse URL', settings: 'Download settings', concurrency: 'Concurrent downloads', retries: 'Retries per segment', timeout: 'Request timeout (seconds)',
  filename: 'File name', credentials: 'Send source site login cookies', rangeStart: 'First segment', rangeEnd: 'Last segment (blank for all)',
  skipBadge: 'Skip missing segments automatically', sourceNote: 'Paste a direct M3U8 URL. Requests go to the source; video processing stays local.',
  quality: 'Choose quality', loadQuality: 'Load this quality', workspace: 'Download task', empty: 'Keep the next frame moving',
  emptyNote: 'Parse a URL to see download progress and the status of each segment.', resume: 'Resume download', pause: 'Pause download',
  downloadAndExport: 'Download and export', resumeAndExport: 'Resume and export', exportAgain: 'Export again',
  retry: 'Retry skipped segments', clear: 'Clear this task’s cache', ready: '{count} segments parsed · {duration}', cached: '{count} cached segments restored',
  liveNote: 'Live playlist: downloads this snapshot only; continuous recording is not supported.', downloading: 'Downloading; missing segments will be skipped',
  paused: 'Paused; completed segments are saved', complete: 'Finished: {done} saved · {skipped} skipped',
  doneLabel: 'Downloaded', skippedLabel: 'Skipped', bytesLabel: 'Cached', durationLabel: 'Retained duration',
  pending: 'Pending', fetching: 'Downloading', retrying: 'Retrying', done: 'Saved', skipped: 'Skipped',
  segments: 'Segment status', segmentLabel: 'Segment {index} · {state} · {attempts} requests', previous: 'Previous', next: 'Next',
  page: 'Page {page} / {pages}', exportTitle: 'Join and export', exportNote: 'Once downloading finishes, segments are remuxed in their original order onto a continuous timeline without re-encoding. Missing footage is removed; you can also export again from here.',
  mp4: 'Export MP4', ts: 'Export TS', report: 'Download gap report', cancelExport: 'Cancel export',
  loadCore: 'Loading local remux engine {percent}%', preparing: 'Preparing segments {done} / {total}', merging: 'Joining timeline and remuxing {percent}%',
  exported: '{format} ready · {size}. Preview or save again.', saveAgain: 'Save video again', preview: 'Exported video preview',
  limitations: 'Processing loads a ~{coreMiB} MiB engine. Standard export is limited to {maxMiB} MiB. Large-video mode writes segments to disk, subject to segment size and free space. The source must allow CORS.',
  gapNote: '{count} segments skipped ({duration}). Missing footage cannot be recovered; later content continues.',
  parseBusy: 'Reading playlist…', clearDone: 'Task cache cleared; you can download again', noneSkipped: 'No segments to retry',
  invalidUrl: 'Enter a valid HTTP / HTTPS video URL.', invalidPlaylist: 'Invalid HLS playlist. Check the URL and playlist content.',
  unsupportedPlaylist: 'Playlists with variable substitution are not supported. Use a resolved media playlist URL.',
  unsupportedEncryption: 'SAMPLE-AES, DRM, or unsupported encryption. Standard AES-128 is supported.',
  externalAudio: 'This quality uses an external audio track, which is not supported. Choose a playlist with included audio.',
  networkError: 'Request failed. Check connectivity, URL expiry, and the source’s CORS policy.', timeoutError: 'Request timed out. Increase the timeout or check connectivity.',
  cacheError: 'Cannot access local cache. Check storage permissions and free space. Existing cache is retained.',
  invalidKey: 'The AES key is not valid 16-byte data. Check access permissions or the source response. Task paused.',
  decryptError: 'AES decryption failed. Check the key or encryption format. Task paused.',
  coreLoadError: 'Could not load the remux engine. Reload or check site assets. Video cache is retained.',
  remuxError: 'Remux failed: damaged segments, codec changes, or incompatible formats. Check the report or try TS. Cache is retained.',
  remuxTimeout: 'Remux timed out. Try a smaller segment range. Cache is retained.',
  exportCancelled: 'Export cancelled. Video cache is retained.', noSegments: 'There are no saved segments to export.',
  exportTooLarge: 'Selected media exceeds {maxMiB} MiB. Use smaller segment ranges for reliable browser exports. Cache is retained.',
  invalidRange: 'The source returned an incorrect byte range.', emptySegment: 'The source returned an empty segment.', invalidMedia: 'The response is not a valid media segment.',
  playlistGap: 'Marked as missing in playlist', httpError: 'Source request failed.', rangeError: 'Invalid segment range. Use segment numbers from this playlist.',
  storageNote: 'Cache stays in this browser. After reloading, parse the same playlist to restore it.', speed: '{speed}/s',
  attribution: 'Reference project', probeSkipped: '{count} damaged segments excluded from the export and recorded in the report.',
};

const ko: typeof zh = {
  ...en,
  source: '영상 소스', url: 'M3U8 재생목록 주소', parse: '링크 분석', settings: '다운로드 설정', concurrency: '동시 다운로드', retries: '재시도 횟수', timeout: '요청 시간 제한(초)',
  filename: '파일 이름', credentials: '소스 사이트 로그인 쿠키 전송', rangeStart: '시작 조각', rangeEnd: '마지막 조각(비워 두면 끝까지)',
  skipBadge: '누락 조각 자동 건너뛰기', sourceNote: 'M3U8 직접 주소를 입력하세요. 소스 서버에 요청하며 영상은 로컬에서 처리합니다.',
  quality: '화질 선택', loadQuality: '선택한 화질 불러오기', workspace: '다운로드 작업', empty: '다음 장면을 이어서 저장', emptyNote: '주소를 분석하면 다운로드 진행 상황과 조각별 상태가 표시됩니다.',
  resume: '다운로드 계속', pause: '다운로드 일시 정지', retry: '건너뛴 조각 재시도', clear: '이 작업의 캐시 삭제',
  downloadAndExport: '다운로드 후 내보내기', resumeAndExport: '계속 후 내보내기', exportAgain: '다시 내보내기',
  ready: '조각 {count}개 분석 완료 · {duration}', cached: '캐시 조각 {count}개 복원', liveNote: '라이브 목록은 현재 스냅샷만 다운로드합니다. 연속 녹화는 지원하지 않습니다.',
  downloading: '다운로드 중입니다. 누락 조각은 자동으로 건너뜁니다.', paused: '일시 정지됨. 완료한 조각은 저장되었습니다.', complete: '완료: 저장 {done}개 · 건너뜀 {skipped}개',
  doneLabel: '다운로드 완료', skippedLabel: '건너뜀', bytesLabel: '캐시 크기', durationLabel: '저장된 길이', pending: '대기', fetching: '다운로드 중', retrying: '재시도 중', done: '저장됨', skipped: '건너뜀',
  segments: '조각 상태', segmentLabel: '조각 {index} · {state} · 요청 {attempts}회', previous: '이전', next: '다음', page: '{page} / {pages}페이지',
  exportTitle: '연결 및 내보내기', exportNote: '다운로드가 끝나면 성공한 조각을 원래 순서대로 재인코딩 없이 연속 시간축으로 연결합니다. 누락 영상은 제외되며, 여기에서 다시 내보낼 수도 있습니다.',
  mp4: 'MP4 내보내기', ts: 'TS 내보내기', report: '누락 보고서 저장', cancelExport: '내보내기 취소', loadCore: '로컬 병합 엔진 로드 중 {percent}%', preparing: '조각 준비 중 {done} / {total}', merging: '시간축 연결 및 파일 생성 중 {percent}%',
  exported: '{format} 생성 완료 · {size}. 미리 보거나 다시 저장할 수 있습니다.', saveAgain: '영상 다시 저장', preview: '내보낸 영상 미리 보기',
  limitations: '처리에 약 {coreMiB} MiB 엔진을 로드합니다. 일반 내보내기는 {maxMiB} MiB까지 지원합니다. 대용량 모드는 세그먼트 크기와 디스크 공간의 제한을 받습니다. 소스 서버가 CORS를 허용해야 합니다.',
  gapNote: '조각 {count}개({duration})를 건너뛰었습니다. 누락 영상은 복원할 수 없으며 이후 내용은 이어집니다.', parseBusy: '재생목록 읽는 중…', clearDone: '작업 캐시를 삭제했습니다. 다시 다운로드할 수 있습니다.', noneSkipped: '재시도할 조각이 없습니다.',
  invalidUrl: '올바른 HTTP / HTTPS 영상 주소를 입력하세요.', invalidPlaylist: '유효한 HLS 목록이 아닙니다. 링크와 내용을 확인하세요.', unsupportedPlaylist: '변수를 사용하는 목록은 지원하지 않습니다. 실제 미디어 목록 주소를 사용하세요.',
  unsupportedEncryption: '지원하지 않는 암호화 또는 DRM입니다. 표준 AES-128을 지원합니다.', externalAudio: '별도 오디오 트랙은 지원하지 않습니다. 오디오가 포함된 목록을 선택하세요.',
  networkError: '요청 실패. 네트워크, 링크 만료 및 소스의 CORS 설정을 확인하세요.', timeoutError: '요청 시간이 초과되었습니다. 제한 시간을 늘리거나 네트워크를 확인하세요.',
  cacheError: '캐시에 접근할 수 없습니다. 저장 권한과 공간을 확인하세요. 기존 캐시는 유지됩니다.', invalidKey: 'AES 키가 유효한 16바이트 데이터가 아닙니다. 권한을 확인하세요. 작업이 일시 정지되었습니다.', decryptError: 'AES 복호화 실패. 키와 형식을 확인하세요. 작업이 일시 정지되었습니다.',
  coreLoadError: '병합 엔진을 로드하지 못했습니다. 새로고침하거나 사이트 리소스를 확인하세요. 캐시는 유지됩니다.', remuxError: '손상된 조각 또는 형식 문제로 병합하지 못했습니다. 보고서를 확인하거나 TS를 선택하세요. 캐시는 유지됩니다.', remuxTimeout: '병합 시간이 초과되었습니다. 더 작은 범위를 선택하세요. 캐시는 유지됩니다.',
  exportCancelled: '내보내기를 취소했습니다. 캐시는 유지됩니다.', noSegments: '내보낼 조각이 없습니다.', exportTooLarge: '선택한 영상이 {maxMiB} MiB를 초과합니다. 작은 조각 범위로 나누세요. 캐시는 유지됩니다.',
  invalidRange: '소스의 바이트 범위가 올바르지 않습니다.', emptySegment: '빈 조각을 반환했습니다.', invalidMedia: '유효한 미디어 조각이 아닙니다.', playlistGap: '목록에서 누락으로 표시됨', httpError: '소스 요청 실패.', rangeError: '올바른 조각 번호 범위를 입력하세요.',
  storageNote: '캐시는 이 브라우저에 저장됩니다. 새로고침 후 같은 목록을 분석하면 복원됩니다.', attribution: '참고 프로젝트', probeSkipped: '손상된 조각 {count}개를 제외하고 보고서에 기록했습니다.',
};

const ja: typeof zh = {
  ...en,
  source: '動画ソース', url: 'M3U8 プレイリストの URL', parse: 'リンクを解析', settings: 'ダウンロード設定', concurrency: '同時ダウンロード数', retries: '再試行回数', timeout: 'タイムアウト（秒）',
  filename: 'ファイル名', credentials: '配信元のログイン Cookie を送信', rangeStart: '開始セグメント', rangeEnd: '終了セグメント（空欄で最後まで）',
  skipBadge: '欠損セグメントを自動スキップ', sourceNote: 'M3U8 の直接 URL を入力してください。配信元にリクエストし、動画はローカルで処理します。',
  quality: '画質を選択', loadQuality: '選択した画質を読み込む', workspace: 'ダウンロードタスク', empty: '次のシーンをつなげて保存', emptyNote: 'リンクを解析すると進捗と各セグメントの状態が表示されます。',
  resume: 'ダウンロード再開', pause: '一時停止', retry: 'スキップした部分を再試行', clear: 'このタスクのキャッシュを削除',
  downloadAndExport: 'ダウンロードして書き出す', resumeAndExport: '再開して書き出す', exportAgain: 'もう一度書き出す',
  ready: '{count} セグメントを解析 · {duration}', cached: '{count} 個のキャッシュを復元', liveNote: 'ライブリストは現在のスナップショットのみ保存します。連続録画には対応していません。',
  downloading: 'ダウンロード中。欠損セグメントは自動でスキップします。', paused: '一時停止しました。完了した部分は保存済みです。', complete: '完了：保存 {done} · スキップ {skipped}',
  doneLabel: '保存済み', skippedLabel: 'スキップ', bytesLabel: 'キャッシュ', durationLabel: '保存する長さ', pending: '待機', fetching: 'ダウンロード中', retrying: '再試行中', done: '保存済み', skipped: 'スキップ',
  segments: 'セグメントの状態', segmentLabel: 'セグメント {index} · {state} · {attempts} 回リクエスト', previous: '前へ', next: '次へ', page: '{page} / {pages} ページ',
  exportTitle: '接続して書き出す', exportNote: 'ダウンロード完了後、成功した部分を元の順序で連続した時間軸に再格納します。再エンコードせず、欠損映像は除外します。ここから再度書き出すこともできます。',
  mp4: 'MP4 を書き出す', ts: 'TS を書き出す', report: '欠損レポートを保存', cancelExport: '書き出しをキャンセル', loadCore: 'ローカルエンジンを読み込み中 {percent}%', preparing: 'セグメント準備中 {done} / {total}', merging: '時間軸を接続して再格納中 {percent}%',
  exported: '{format} を作成 · {size}。プレビューまたは再保存できます。', saveAgain: '動画を再保存', preview: '書き出した動画のプレビュー',
  limitations: '処理時に約 {coreMiB} MiB のエンジンを読み込みます。通常の出力上限は {maxMiB} MiB。大容量モードにはセグメントサイズと空き容量の制限があります。配信元の CORS 許可が必要です。',
  gapNote: '{count} 個（{duration}）をスキップしました。欠損映像は復元できませんが、後続の映像は接続します。', parseBusy: 'プレイリストを読み込み中…', clearDone: 'キャッシュを削除しました。再ダウンロードできます。', noneSkipped: '再試行するセグメントはありません。',
  invalidUrl: '有効な HTTP / HTTPS の動画 URL を入力してください。', invalidPlaylist: '無効な HLS リストです。リンクと内容を確認してください。', unsupportedPlaylist: '変数を含むリストには対応していません。展開済みメディアリストを使用してください。',
  unsupportedEncryption: '非対応の暗号化または DRM です。標準 AES-128 に対応しています。', externalAudio: '外部音声トラックは非対応です。音声を含むリストを選んでください。',
  networkError: 'リクエスト失敗。ネットワーク、リンクの期限、配信元の CORS 設定を確認してください。', timeoutError: 'タイムアウトしました。制限時間を増やすかネットワークを確認してください。',
  cacheError: 'キャッシュにアクセスできません。保存権限と空き容量を確認してください。既存データは保持されます。', invalidKey: 'AES キーが有効な 16 バイトではありません。権限を確認してください。タスクは一時停止しました。', decryptError: 'AES 復号に失敗しました。キーと形式を確認してください。タスクは一時停止しました。',
  coreLoadError: 'エンジンの読み込みに失敗しました。再読み込みするかサイトのリソースを確認してください。キャッシュは保持されます。', remuxError: '破損セグメントや形式の問題で再格納に失敗しました。レポートを確認するか TS をお試しください。キャッシュは保持されます。', remuxTimeout: '処理がタイムアウトしました。範囲を小さくしてください。キャッシュは保持されます。',
  exportCancelled: '書き出しをキャンセルしました。キャッシュは保持されます。', noSegments: '書き出せるセグメントがありません。', exportTooLarge: '選択した動画が {maxMiB} MiB を超えています。範囲を分けてください。キャッシュは保持されます。',
  invalidRange: '配信元のバイト範囲が正しくありません。', emptySegment: '空のセグメントが返されました。', invalidMedia: '有効なメディアセグメントではありません。', playlistGap: 'リストで欠損と指定', httpError: '配信元へのリクエスト失敗。', rangeError: '正しいセグメント番号の範囲を入力してください。',
  storageNote: 'キャッシュはこのブラウザに保存されます。再読み込み後に同じリストを解析すると復元できます。', attribution: '参考プロジェクト', probeSkipped: '破損した {count} セグメントを除外し、レポートに記録しました。',
};

export type HlsCopy = typeof zh & typeof streamTranslations.zh;
export function hlsCopy(lang: Lang): HlsCopy {
  const source = lang === 'en' ? en : lang === 'ko' ? ko : lang === 'ja' ? ja : zh;
  const tokens = { maxMiB: HLS_CONFIG.limits.exportBytes / 1048576, coreMiB: Math.ceil(HLS_CONFIG.core.estimatedBytes / 1048576), segmentMiB: HLS_CONFIG.stream.segmentBytes / 1048576 };
  const extra = lang === 'en' ? streamTranslations.en : lang === 'ko' ? streamTranslations.ko : lang === 'ja' ? streamTranslations.ja : streamTranslations.zh;
  return Object.fromEntries(Object.entries({ ...source, ...extra }).map(([key, value]) => {
    const localized = lang === 'tw' ? chineseS2t.s2t(value) : value;
    return [key, localized.replace(/\{(maxMiB|coreMiB|segmentMiB)\}/g, (_, token) => String(tokens[token]))];
  })) as HlsCopy;
}
