const zh = {
  formatLabel: '导出格式', originalFormat: '原格式（自动识别）', exportSelected: '按所选格式导出',
  streamMode: '特大视频：边下载边保存', streamNote: '逐片写入磁盘，降低内存占用。保留本地分片用于刷新恢复，需要额外磁盘空间。',
  streamPrepare: '准备流式保存', streamChoose: '选择文件并开始', streamReady: '已识别 {format}，点击“选择文件并开始”设置保存位置。',
  chooseAnotherFile: '另选保存位置',
  keyRequestError: '无法读取 AES 密钥，任务已暂停。检查密钥链接、登录授权和跨域设置，缓存保留。',
  initError: '初始化片段不可用，任务已暂停。检查来源或登录授权后重试，缓存保留。',
  streamUnsupported: '此浏览器不支持直接写入文件。请使用支持该功能的 Chrome／Edge，或关闭特大模式使用普通导出。',
  writtenLabel: '已写入磁盘', streamWritten: '{count} 个分片 · {size} 已写入', streamComplete: '{format} 文件已保存 · {size}。本地缓存仍可用于重建。',
  streamPaused: '已暂停，写入流保留。可继续下载，或保存已完成的部分。', savePartial: '保存当前部分', partialSaved: '已保存完整分片组成的部分文件 · {size}。继续任务时将从缓存重建文件。',
  restoreTask: '恢复上次流式任务', restoreNote: '已找到上次任务。恢复会复用已下载分片；重新授权后逐片重建输出文件。',
  streamRestored: '已恢复 {count} 个缓存分片。输出文件将顺序重建，不重复下载这些分片。', rebuildNote: '补回已跳过的分片需要重建文件；已下载分片会从本地复用。',
  fileCancelled: '已取消选择保存位置。任务和缓存保留。', filePermissionError: '无法获得文件写入权限。重新授权或选择新的保存位置，缓存保留。',
  fileWriteError: '文件写入失败。检查磁盘空间、权限或设备连接，再从缓存重建文件。', streamChanged: '编码、音轨结构或时间轴不兼容，已停止追加。缓存保留，可选择范围分别保存。',
  segmentTooLarge: '单个分片超过流式模式的 {segmentMiB} MiB 安全上限，任务已暂停。请选择更低码率或更短分片的来源。',
  cacheBlocked: '缓存升级被另一个页面阻止。关闭其他 CloverTools 下载页面后刷新，原缓存保留。',
};
const en: typeof zh = {
  formatLabel: 'Output format', originalFormat: 'Source format (automatic)', exportSelected: 'Export selected format',
  streamMode: 'Large video: save while downloading', streamNote: 'Write one segment at a time to reduce memory use. Local segments remain available for recovery and require extra disk space.',
  streamPrepare: 'Prepare streaming save', streamChoose: 'Choose file and start', streamReady: 'Detected {format}. Choose a file to start saving.',
  chooseAnotherFile: 'Choose another location',
  keyRequestError: 'The AES key could not be loaded. The task is paused. Check the key URL, authorization and CORS. The cache is retained.',
  initError: 'The initialization segment is unavailable. The task is paused. Check the source or authorization and retry. The cache is retained.',
  streamUnsupported: 'Direct file writing is unavailable. Use a compatible Chrome / Edge browser, or turn off large-video mode for standard export.',
  writtenLabel: 'Written to disk', streamWritten: '{count} segments · {size} written', streamComplete: '{format} saved · {size}. Local segments remain available for rebuilding.',
  streamPaused: 'Paused with the file stream retained. Resume downloading or save the completed portion.', savePartial: 'Save completed portion', partialSaved: 'Saved complete segments · {size}. Resuming will rebuild the file from the local cache.',
  restoreTask: 'Restore streaming task', restoreNote: 'A previous task is available. Restore cached segments and authorize the file again to rebuild it sequentially.',
  streamRestored: 'Restored {count} cached segments. The file will be rebuilt without downloading them again.', rebuildNote: 'Recovering skipped segments requires rebuilding the file. Cached segments will be reused.',
  fileCancelled: 'File selection cancelled. The task and cache are retained.', filePermissionError: 'File write permission is unavailable. Authorize again or select a new location. The cache is retained.',
  fileWriteError: 'File writing failed. Check disk space, permissions or the device connection, then rebuild from the cache.', streamChanged: 'Incompatible codecs, tracks or timestamps. Appending stopped and the cache is retained. Save separate ranges.',
  segmentTooLarge: 'A segment exceeds the {segmentMiB} MiB streaming safety limit. The task is paused. Choose a source with a lower bitrate or shorter segments.',
  cacheBlocked: 'Another page is blocking the cache upgrade. Close other CloverTools downloader pages and reload. Existing data is retained.',
};
const ko: typeof zh = {
  formatLabel: '출력 형식', originalFormat: '원본 형식 (자동 감지)', exportSelected: '선택한 형식으로 저장',
  streamMode: '대용량 영상: 다운로드하며 저장', streamNote: '세그먼트를 순서대로 디스크에 기록해 메모리 사용을 줄입니다. 복구용 로컬 세그먼트에 추가 디스크 공간이 필요합니다.',
  streamPrepare: '스트리밍 저장 준비', streamChoose: '파일 선택 후 시작', streamReady: '{format} 형식을 감지했습니다. 파일을 선택하고 저장을 시작하세요.',
  chooseAnotherFile: '다른 저장 위치 선택',
  keyRequestError: 'AES 키를 읽을 수 없어 일시 중지했습니다. 키 링크, 로그인 권한 및 CORS 설정을 확인하세요. 캐시는 유지됩니다.',
  initError: '초기화 세그먼트를 사용할 수 없어 일시 중지했습니다. 소스 또는 로그인 권한을 확인한 후 재시도하세요. 캐시는 유지됩니다.',
  streamUnsupported: '이 브라우저는 직접 파일 쓰기를 지원하지 않습니다. 호환되는 Chrome / Edge를 사용하거나 대용량 모드를 끄세요.',
  writtenLabel: '디스크에 기록', streamWritten: '{count}개 세그먼트 · {size} 기록', streamComplete: '{format} 저장 완료 · {size}. 로컬 세그먼트로 다시 생성할 수 있습니다.',
  streamPaused: '파일 스트림을 유지한 채 일시 중지했습니다. 계속하거나 완료된 부분을 저장하세요.', savePartial: '완료된 부분 저장', partialSaved: '완전한 세그먼트를 저장했습니다 · {size}. 계속하면 로컬 캐시로 파일을 다시 생성합니다.',
  restoreTask: '이전 스트리밍 작업 복구', restoreNote: '이전 작업이 있습니다. 캐시를 복구하고 파일 권한을 다시 부여하면 순서대로 파일을 다시 생성합니다.',
  streamRestored: '캐시 세그먼트 {count}개를 복구했습니다. 재다운로드 없이 파일을 다시 생성합니다.', rebuildNote: '건너뛴 부분을 복구하면 파일을 다시 생성해야 합니다. 캐시를 재사용합니다.',
  fileCancelled: '저장 위치 선택을 취소했습니다. 작업과 캐시는 유지됩니다.', filePermissionError: '파일 쓰기 권한을 얻을 수 없습니다. 다시 허용하거나 새 위치를 선택하세요. 캐시는 유지됩니다.',
  fileWriteError: '파일 쓰기에 실패했습니다. 디스크 공간, 권한 또는 장치 연결을 확인하고 캐시에서 다시 생성하세요.', streamChanged: '코덱, 트랙 또는 시간축이 호환되지 않아 추가를 중지했습니다. 캐시는 유지됩니다. 범위를 나누어 저장하세요.',
  segmentTooLarge: '세그먼트가 {segmentMiB} MiB 안전 한도를 초과하여 일시 중지했습니다. 낮은 비트레이트나 짧은 세그먼트의 소스를 선택하세요.',
  cacheBlocked: '다른 페이지가 캐시 업그레이드를 막고 있습니다. 다른 CloverTools 다운로드 페이지를 닫고 새로 고침하세요. 기존 캐시는 유지됩니다.',
};
const ja: typeof zh = {
  formatLabel: '出力形式', originalFormat: '元の形式（自動判別）', exportSelected: '選択した形式で保存',
  streamMode: '大容量動画：ダウンロードしながら保存', streamNote: 'セグメントを順番にディスクへ書き込み、メモリ使用量を抑えます。復元用のローカルデータには追加の空き容量が必要です。',
  streamPrepare: 'ストリーミング保存を準備', streamChoose: 'ファイルを選んで開始', streamReady: '{format} を検出しました。保存先を選んで開始してください。',
  chooseAnotherFile: '別の保存先を選択',
  keyRequestError: 'AES キーを取得できないため一時停止しました。キー URL、ログイン権限、CORS 設定を確認してください。キャッシュは保持されます。',
  initError: '初期化セグメントが利用できないため一時停止しました。配信元やログイン権限を確認して再試行してください。キャッシュは保持されます。',
  streamUnsupported: 'このブラウザでは直接ファイルに書き込めません。対応する Chrome / Edge を使うか、大容量モードをオフにしてください。',
  writtenLabel: 'ディスクに書き込み', streamWritten: '{count} セグメント · {size} 書き込み', streamComplete: '{format} を保存しました · {size}。ローカルデータで再生成できます。',
  streamPaused: '書き込みストリームを保持して一時停止しました。再開するか、完了部分を保存できます。', savePartial: '完了部分を保存', partialSaved: '完全なセグメントを保存しました · {size}。再開時はキャッシュからファイルを再生成します。',
  restoreTask: '前の保存タスクを復元', restoreNote: '前のタスクがあります。キャッシュを復元し、ファイルを再承認すると順番に再生成できます。',
  streamRestored: '{count} 個のキャッシュを復元しました。再ダウンロードせずファイルを再生成します。', rebuildNote: 'スキップした部分を補うにはファイルの再生成が必要です。キャッシュを再利用します。',
  fileCancelled: '保存先の選択をキャンセルしました。タスクとキャッシュは保持されます。', filePermissionError: 'ファイルの書き込み権限を取得できません。再承認するか別の保存先を選んでください。キャッシュは保持されます。',
  fileWriteError: '書き込みに失敗しました。空き容量、権限、機器の接続を確認し、キャッシュから再生成してください。', streamChanged: 'コーデック、トラック、時間軸に互換性がないため追加を停止しました。キャッシュは保持されます。範囲を分けて保存してください。',
  segmentTooLarge: 'セグメントが安全上限 {segmentMiB} MiB を超えたため一時停止しました。低ビットレートか短いセグメントの配信元を選んでください。',
  cacheBlocked: '別のページがキャッシュ更新をブロックしています。他の CloverTools ダウンロードページを閉じて再読み込みしてください。既存データは保持されます。',
};
export const streamTranslations = { zh, en, ko, ja };
