export type ToolCategory = 'dev' | 'daily' | 'fun';

export interface ToolMeta {
  slug: string;
  name: string;
  oneLiner: string;
  description: string;
  icon: string;
  keywords: string[];
  tier: 'P0' | 'P1';
  worker?: boolean;
  legacyPath?: string;
}

export interface CategoryMeta {
  id: ToolCategory;
  name: string;
  icon: string;
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'dev',
    name: '开发实用',
    icon: 'bi-code-square',
    blurb: '编码、格式化、加解密与调试，开发日常高频刚需。',
  },
  {
    id: 'daily',
    name: '日常实用',
    icon: 'bi-house-heart',
    blurb: '日期、理财、换算与效率小工具，生活工作两相宜。',
  },
  {
    id: 'fun',
    name: '趣味工具',
    icon: 'bi-emoji-sunglasses',
    blurb: '减压、娱乐与创意小玩意，给忙碌的日常加点乐趣。',
  },
];

export const TOOLS: Record<ToolCategory, ToolMeta[]> = {
  dev: [
    {
      slug: 'json-formatter',
      name: 'JSON 格式化与校验',
      oneLiner: '格式化、压缩、校验 JSON，实时定位语法错误。',
      description: '在线 JSON 格式化、压缩与校验工具，支持缩进自定义、错误行号定位，纯浏览器处理不泄露数据。',
      icon: 'bi-braces',
      keywords: ['json格式化', 'json校验', 'json压缩'],
      tier: 'P0',
      legacyPath: '/tools/code/json-compress.html',
    },
    {
      slug: 'json-convert',
      name: 'JSON 转 CSV/Excel',
      oneLiner: '一键把 JSON 数组转为 CSV 或 Excel 表格。',
      description: '把 JSON 数组数据转换为 CSV 或 Excel 文件，支持表头定制与下载，纯浏览器处理。',
      icon: 'bi-table',
      keywords: ['json转csv', 'json转excel', 'json转表格'],
      tier: 'P0',
      legacyPath: '/tools/code/json2csv.html',
    },
    {
      slug: 'json-codegen',
      name: 'JSON 转实体类',
      oneLiner: '从 JSON 生成 TypeScript、Go、Java、C# 类型定义。',
      description: '根据 JSON 示例数据生成 TypeScript 接口、Go Struct、Java 实体类与 C# 模型，减少手写类型代码。',
      icon: 'bi-file-code',
      keywords: ['json转ts', 'json转go', 'json转java', 'json转csharp'],
      tier: 'P1',
      legacyPath: '/tools/code/json2ts.html',
    },
    {
      slug: 'json-xml-yaml',
      name: 'JSON/XML/YAML 互转',
      oneLiner: '三种数据格式无损互转，保留结构层次。',
      description: 'JSON、XML、YAML 三种数据格式相互转换，支持缩进配置，适合接口数据迁移与配置文件处理。',
      icon: 'bi-arrow-left-right',
      keywords: ['json转xml', 'json转yaml', 'xml转json', 'yaml转json'],
      tier: 'P0',
      legacyPath: '/tools/json/xml.html',
    },
    {
      slug: 'jsonpath',
      name: 'JSONPath 查询',
      oneLiner: '用 JSONPath 表达式从 JSON 中提取数据。',
      description: '在线 JSONPath 解析器，输入表达式实时高亮匹配结果，支持常见 JSONPath 语法。',
      icon: 'bi-signpost-split',
      keywords: ['jsonpath', 'json查询', 'jsonpath解析'],
      tier: 'P1',
      legacyPath: '/tools/code/jsonpath.html',
    },
    {
      slug: 'diff',
      name: '文本差异对比',
      oneLiner: '逐行对比两段文本，差异高亮一目了然。',
      description: '两段文本逐行差异对比，支持行内级高亮与统计，适合配置、代码与 JSON 内容对比。',
      icon: 'bi-file-diff',
      keywords: ['文本对比', 'diff', '代码对比', 'json对比'],
      tier: 'P0',
      legacyPath: '/tools/text/diff.html',
    },
    {
      slug: 'base64',
      name: 'Base64 编解码',
      oneLiner: '文本与 Base64 互转，支持图片数据转码。',
      description: 'Base64 编码与解码工具，支持 UTF-8 中文、URL 安全模式与图片转 Base64 数据。',
      icon: 'bi-code-square',
      keywords: ['base64', 'base64编码', 'base64解码'],
      tier: 'P0',
      legacyPath: '/tools/code/base64.html',
    },
    {
      slug: 'url-encode',
      name: 'URL 编解码',
      oneLiner: 'URL 编码、解码与参数还原，中文不乱码。',
      description: 'URL 编码与解码工具，正确处理中文与特殊字符，支持完整组件与查询参数两种模式。',
      icon: 'bi-link-45deg',
      keywords: ['url编码', 'url解码', 'urlencode'],
      tier: 'P0',
      legacyPath: '/tools/code/url.html',
    },
    {
      slug: 'html-formatter',
      name: 'HTML 格式化与实体转换',
      oneLiner: 'HTML 美化压缩，标签实体编码解码。',
      description: 'HTML 格式化、压缩以及 HTML 实体编码解码，适合邮件模板、富文本内容处理。',
      icon: 'bi-filetype-html',
      keywords: ['html格式化', 'html压缩', 'html实体编码'],
      tier: 'P0',
      legacyPath: '/tools/code/html-formatter.html',
    },
    {
      slug: 'css-formatter',
      name: 'CSS 格式化与单位换算',
      oneLiner: 'CSS 美化压缩，px/rem/em/vw 实时互转。',
      description: 'CSS 格式化与压缩工具，附带 px、rem、em、vw 等常用单位换算，设计还原更顺手。',
      icon: 'bi-filetype-css',
      keywords: ['css格式化', 'css压缩', 'css单位换算'],
      tier: 'P0',
      legacyPath: '/tools/code/css.html',
    },
    {
      slug: 'js-formatter',
      name: 'JavaScript 格式化',
      oneLiner: 'JS 代码美化与压缩，兼容现代语法。',
      description: 'JavaScript 代码格式化与压缩工具，支持 ES 现代语法与配置项，粘贴即可整理。',
      icon: 'bi-filetype-js',
      keywords: ['javascript格式化', 'js压缩', 'js美化'],
      tier: 'P0',
      legacyPath: '/tools/code/javascript.html',
    },
    {
      slug: 'sql-formatter',
      name: 'SQL 格式化',
      oneLiner: 'SQL 语句美化缩进，支持多种方言。',
      description: 'SQL 格式化工具，支持 MySQL、PostgreSQL、SQL Server 等方言，语句层次清晰。',
      icon: 'bi-database',
      keywords: ['sql格式化', 'sql美化', 'sql缩进'],
      tier: 'P1',
      legacyPath: '/tools/code/sql-formatter.html',
    },
    {
      slug: 'xml-formatter',
      name: 'XML 格式化与压缩',
      oneLiner: 'XML 美化、压缩与合法性校验。',
      description: 'XML 格式化、压缩与校验工具，错误提示清晰，适合接口报文与配置文件处理。',
      icon: 'bi-filetype-xml',
      keywords: ['xml格式化', 'xml压缩', 'xml校验'],
      tier: 'P0',
      legacyPath: '/tools/code/xml-format.html',
    },
    {
      slug: 'markdown',
      name: 'Markdown 在线编辑器',
      oneLiner: '工具栏、快捷键、实时预览，写作排版所见即所得。',
      description: '成熟的 Markdown 在线编辑器：工具栏格式化、快捷键、分屏实时预览、草稿自动保存、导出 Markdown/HTML。',
      icon: 'bi-markdown',
      keywords: ['markdown编辑器', 'markdown在线', 'markdown预览', 'markdown转html'],
      tier: 'P0',
      legacyPath: '/tools/code/markdown.html',
    },
    {
      slug: 'regex-tester',
      name: '正则表达式测试',
      oneLiner: '实时匹配高亮，附带常用表达式库。',
      description: '正则表达式在线测试器，实时高亮匹配结果、展示捕获组，内置常用正则示例库。',
      icon: 'bi-asterisk',
      keywords: ['正则测试', '正则表达式', 'regex'],
      tier: 'P0',
      legacyPath: '/tools/code/regex-tester.html',
    },
    {
      slug: 'text-transform',
      name: '文本转换工具',
      oneLiner: '大小写、驼峰下划线、全角半角一键互转。',
      description: '文本大小写转换、驼峰与下划线互转、全角半角转换，批量处理粘贴即用。',
      icon: 'bi-textarea-t',
      keywords: ['大小写转换', '驼峰转换', '全角半角', '下划线转驼峰'],
      tier: 'P0',
      legacyPath: '/tools/text/case.html',
    },
    {
      slug: 'text-toolbox',
      name: '文本处理工具',
      oneLiner: '去重、排序、反转、去除空行，批量清洗。',
      description: '文本批量处理：去重、排序、反转、去除空行、统计行数，适合日志与列表数据清洗。',
      icon: 'bi-list-check',
      keywords: ['文本去重', '文本排序', '去除空行', '文本反转'],
      tier: 'P1',
      legacyPath: '/tools/text/dedupe.html',
    },
    {
      slug: 'jianfan',
      name: '简繁转换',
      oneLiner: '简体繁体互转，保留用词习惯。',
      description: '简体中文与繁体中文互转工具，正确处理多音字与地区用词差异。',
      icon: 'bi-arrow-repeat',
      keywords: ['简繁转换', '繁体转简体', '简体转繁体'],
      tier: 'P0',
      legacyPath: '/tools/text/jianfan.html',
    },
    {
      slug: 'pinyin',
      name: '汉字转拼音',
      oneLiner: '中文转拼音，支持声调与首字母模式。',
      description: '汉字转拼音工具，支持全拼、声调、首字母多种输出模式，可用于搜索与 URL 生成。',
      icon: 'bi-translate',
      keywords: ['汉字转拼音', '拼音转换', '中文拼音'],
      tier: 'P1',
      legacyPath: '/tools/text/pinyin.html',
    },
    {
      slug: 'cron',
      name: 'Cron 表达式工具',
      oneLiner: '解析表达式，预览未来执行时间。',
      description: 'Cron 表达式解析与生成工具，实时展示下一次执行时间与调度日历，支持 5/6/7 段格式。',
      icon: 'bi-calendar2-week',
      keywords: ['cron表达式', 'cron解析', '定时任务'],
      tier: 'P0',
      legacyPath: '/tools/code/cron-parser.html',
    },
    {
      slug: 'base-converter',
      name: '进制转换',
      oneLiner: '二进制、八进制、十进制、十六进制互转。',
      description: '数字进制互转工具，支持二进制、八进制、十进制、十六进制与补码表示。',
      icon: 'bi-123',
      keywords: ['进制转换', '二进制转十六进制', '十六进制'],
      tier: 'P0',
      legacyPath: '/tools/dev-tools/base-converter.html',
    },
    {
      slug: 'unicode-converter',
      name: 'Unicode/ASCII 转换',
      oneLiner: '字符与 \\uXXXX 转义互转，ASCII 码表速查。',
      description: 'Unicode 与 ASCII 转换工具，支持中文转 \\u 编码、ASCII 码表查询与字符互转。',
      icon: 'bi-fonts',
      keywords: ['unicode转换', 'ascii码', '\\u编码'],
      tier: 'P1',
      legacyPath: '/tools/code/unicode-converter.html',
    },
    {
      slug: 'hash',
      name: 'Hash 生成器',
      oneLiner: 'MD5、SHA 系列、Keccak 与文件哈希计算。',
      description: '在线 Hash 计算工具，支持 MD5、SHA-1、SHA-256、SHA-512、Keccak 以及文件哈希，全部在浏览器完成。',
      icon: 'bi-fingerprint',
      keywords: ['md5加密', 'sha256', '文件哈希', 'hash计算'],
      tier: 'P0',
      legacyPath: '/tools/format-conversion/hash-generator.html',
    },
    {
      slug: 'symmetric-encrypt',
      name: '对称加密工具',
      oneLiner: 'AES、DES、RC4、Rabbit 加解密，浏览器内完成。',
      description: 'AES、DES、RC4、Rabbit 等对称加密算法加解密工具，支持多种填充模式与输出格式。',
      icon: 'bi-lock',
      keywords: ['aes加密', 'des加密', 'rc4加密', '对称加密'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/aes.html',
    },
    {
      slug: 'rsa-encrypt',
      name: 'RSA 加解密',
      oneLiner: '密钥生成、加密、解密、签名一站式。',
      description: 'RSA 密钥对生成与加解密工具，支持签名验签与 PEM 格式导入导出。',
      icon: 'bi-key',
      keywords: ['rsa加密', 'rsa解密', 'rsa密钥生成'],
      tier: 'P1',
      legacyPath: '/tools/encrypt/rsa.html',
    },
    {
      slug: 'bcrypt',
      name: 'Bcrypt 校验',
      oneLiner: '生成 Bcrypt 哈希并校验密码。',
      description: 'Bcrypt 密码哈希生成与校验工具，支持自定义轮数（cost factor），常用于后端密码存储。',
      icon: 'bi-shield-check',
      keywords: ['bcrypt', 'bcrypt加密', 'bcrypt校验'],
      tier: 'P1',
      legacyPath: '/tools/encrypt/bcrypt.html',
    },
    {
      slug: 'jwt-decoder',
      name: 'JWT 解码器',
      oneLiner: '解析 JWT 三段结构，Payload 一目了然。',
      description: 'JWT 在线解码工具，解析 Header 与 Payload，支持 HS256 签名验签。',
      icon: 'bi-file-lock',
      keywords: ['jwt解码', 'jwt解析', 'token解析'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/jwt.html',
    },
    {
      slug: 'password-strength',
      name: '密码强度检测',
      oneLiner: '实时评估密码强度，指出薄弱点。',
      description: '密码强度检测工具，从长度、字符组合、常见密码库等多维度评分并给出改进建议。',
      icon: 'bi-shield-exclamation',
      keywords: ['密码强度', '密码检测', '密码安全'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/password-strength.html',
    },
    {
      slug: 'password-generator',
      name: '随机密码生成',
      oneLiner: '按规则生成高强度随机密码。',
      description: '随机密码生成器，可配置长度与字符集，基于密码学安全随机源，一键复制。',
      icon: 'bi-dice-5',
      keywords: ['密码生成', '随机密码', '强密码'],
      tier: 'P0',
      legacyPath: '/tools/code/password-generator.html',
    },
    {
      slug: 'uuid-generator',
      name: 'UUID/NanoID 生成',
      oneLiner: '批量生成 UUID v4/v7 与 NanoID。',
      description: 'UUID v4、v7 与 NanoID 批量生成工具，支持数量、大小写与分隔符设置。',
      icon: 'bi-hash',
      keywords: ['uuid生成', 'nanoid', 'uuid'],
      tier: 'P0',
      legacyPath: '/tools/dev-tools/uuid-generator.html',
    },
    {
      slug: 'qrcode',
      name: '二维码/条形码生成',
      oneLiner: '文本转二维码或条形码，支持配色下载。',
      description: '在线二维码与条形码生成器，支持容错级别、颜色定制与 PNG 下载。',
      icon: 'bi-qr-code',
      keywords: ['二维码生成', '条形码生成', 'qr码'],
      tier: 'P0',
      legacyPath: '/tools/image/qrcode-generator.html',
    },
    {
      slug: 'http-tester',
      name: 'HTTP 接口测试',
      oneLiner: '构造请求调试接口，查看响应与耗时。',
      description: 'HTTP 接口测试工具，支持方法、请求头、Body 配置，实时展示状态码、响应头与耗时。',
      icon: 'bi-send',
      keywords: ['http测试', '接口测试', 'api测试'],
      tier: 'P0',
      legacyPath: '/tools/network/api-tester.html',
    },
    {
      slug: 'ip-lookup',
      name: 'IP 地址查询',
      oneLiner: '查询本机或指定 IP 的归属地与运营商。',
      description: 'IP 地址归属地查询工具，支持本机 IP 与任意 IPv4 查询，返回国家、地区与运营商信息。',
      icon: 'bi-globe2',
      keywords: ['ip查询', 'ip归属地', 'ip地址查询'],
      tier: 'P0',
      worker: true,
      legacyPath: '/tools/network/ip-lookup.html',
    },
    {
      slug: 'ua-parser',
      name: 'User-Agent 解析',
      oneLiner: '解析 UA 串，识别浏览器、系统与设备。',
      description: 'User-Agent 解析工具，从 UA 字符串中识别浏览器、操作系统与设备类型。',
      icon: 'bi-pc-display',
      keywords: ['ua解析', 'user-agent', '浏览器识别'],
      tier: 'P1',
      legacyPath: '/tools/code/ua-parser.html',
    },
    {
      slug: 'url-parse',
      name: 'URL 参数解析',
      oneLiner: '拆分 URL 各组件，参数表格化展示。',
      description: 'URL 结构解析工具，拆分协议、域名、路径、查询参数与锚点，参数以表格展示。',
      icon: 'bi-diagram-3',
      keywords: ['url解析', 'url参数', '链接参数'],
      tier: 'P0',
      legacyPath: '/tools/network/url-parse.html',
    },
    {
      slug: 'color-convert',
      name: '颜色转换与取色',
      oneLiner: 'HEX、RGB、HSL 互转，取色器实时预览。',
      description: '颜色格式转换工具，支持 HEX、RGB、HSL 互转与屏幕取色，实时预览色值与对比度。',
      icon: 'bi-palette',
      keywords: ['颜色转换', 'hex转rgb', '取色器'],
      tier: 'P0',
      legacyPath: '/tools/format-conversion/color-converter.html',
    },
    {
      slug: 'image-to-base64',
      name: '图片转 Base64',
      oneLiner: '图片文件转 Base64，用于内联与传输。',
      description: '本地图片转 Base64 数据工具，支持压缩选项与多种输出格式，方便嵌入代码与传输。',
      icon: 'bi-image',
      keywords: ['图片转base64', '图片base64', 'base64图片'],
      tier: 'P1',
      legacyPath: '/tools/format-conversion/img2base64.html',
    },
  ],
  daily: [
    {
      slug: 'calendar',
      name: '在线万年历',
      oneLiner: '公历农历对照、节气和节假日查询。',
      description: '在线万年历，公历农历对照展示，支持二十四节气、节假日与黄历信息查询。',
      icon: 'bi-calendar3',
      keywords: ['万年历', '农历', '节气'],
      tier: 'P0',
      legacyPath: '/tools/time/calendar.html',
    },
    {
      slug: 'lunar-converter',
      name: '公历农历互转',
      oneLiner: '公历与农历日期双向转换。',
      description: '公历农历日期互转工具，支持农历闰月，快速换算生日与纪念日。',
      icon: 'bi-moon-stars',
      keywords: ['公历转农历', '农历转公历', '农历查询'],
      tier: 'P0',
      legacyPath: '/tools/time/lunar-solar-converter.html',
    },
    {
      slug: 'world-clock',
      name: '世界时钟',
      oneLiner: '全球多时区时间对照与转换。',
      description: '世界时钟与时区转换工具，多城市时间对照、任意时区换算，出差协作必备。',
      icon: 'bi-globe-americas',
      keywords: ['世界时钟', '时区转换', '多时区'],
      tier: 'P0',
      legacyPath: '/tools/time/world.html',
    },
    {
      slug: 'date-diff',
      name: '日期间隔计算',
      oneLiner: '两个日期相差天数，含周数与日历月换算。',
      description: '日期间隔计算工具，计算两日期相差天数、周数、月数，支持日期加减天数。',
      icon: 'bi-hourglass-split',
      keywords: ['日期间隔', '日期计算', '相差天数'],
      tier: 'P0',
      legacyPath: '/tools/time/interval.html',
    },
    {
      slug: 'timestamp',
      name: '时间戳转换',
      oneLiner: '秒/毫秒时间戳与日期实时互转。',
      description: 'Unix 时间戳与日期时间互转，自动识别秒与毫秒，支持实时时钟与批量转换。',
      icon: 'bi-clock-history',
      keywords: ['时间戳转换', 'unix时间戳', '时间戳在线'],
      tier: 'P0',
      legacyPath: '/tools/time/timestamp.html',
    },
    {
      slug: 'workday',
      name: '工作日计算器',
      oneLiner: '计算两个日期之间的工作日天数。',
      description: '工作日计算器，排除周末与法定节假日，统计两个日期之间的实际工作日。',
      icon: 'bi-briefcase',
      keywords: ['工作日计算', '工作日天数', '考勤计算'],
      tier: 'P1',
      legacyPath: '/tools/time/workday-calculator.html',
    },
    {
      slug: 'age-calculator',
      name: '年龄计算器',
      oneLiner: '精确到天与时刻的年龄计算。',
      description: '年龄计算器，从出生日期精确计算周岁、虚岁与出生天数。',
      icon: 'bi-person',
      keywords: ['年龄计算', '周岁', '出生天数'],
      tier: 'P1',
      legacyPath: '/tools/time/age.html',
    },
    {
      slug: 'timer',
      name: '倒计时与秒表',
      oneLiner: '在线倒计时与秒表，专注计时两不误。',
      description: '在线倒计时与秒表工具，支持自定义时长、计时结束提醒，适合专注与活动计时。',
      icon: 'bi-stopwatch',
      keywords: ['倒计时', '秒表', '计时器'],
      tier: 'P0',
      legacyPath: '/tools/time/countdown.html',
    },
    {
      slug: 'bmi',
      name: 'BMI 计算器',
      oneLiner: '身高体重算 BMI，附健康区间参考。',
      description: 'BMI 体重指数计算器，根据身高体重计算指数并对照健康区间给出参考。',
      icon: 'bi-heart-pulse',
      keywords: ['bmi计算', '体重指数', '健康指数'],
      tier: 'P0',
      legacyPath: '/tools/life/bmi-calculator.html',
    },
    {
      slug: 'salary',
      name: '工资与五险一金计算',
      oneLiner: '税前税后工资与五险一金明细计算。',
      description: '税后工资计算器，包含五险一金、个税明细，按城市比例配置，收入构成一目了然。',
      icon: 'bi-cash-stack',
      keywords: ['税后工资', '五险一金', '工资计算器'],
      tier: 'P0',
      legacyPath: '/tools/life/salary.html',
    },
    {
      slug: 'finance',
      name: '理财计算器',
      oneLiner: '贷款、复利与百分比计算汇总。',
      description: '理财计算器，支持贷款月供、复利收益与百分比计算，决策参考更清晰。',
      icon: 'bi-percent',
      keywords: ['贷款计算', '复利计算', '百分比计算'],
      tier: 'P1',
      legacyPath: '/tools/math/loan-calculator.html',
    },
    {
      slug: 'calculator',
      name: '多功能计算器',
      oneLiner: '标准与科学计算一体，常用函数齐全。',
      description: '多功能计算器，支持四则运算、阶乘、幂、开方、质数判定与数列求和等常用数学函数。',
      icon: 'bi-calculator',
      keywords: ['计算器', '科学计算器', '数学计算'],
      tier: 'P0',
      legacyPath: '/tools/math/calculator.html',
    },
    {
      slug: 'unit-converter',
      name: '单位换算',
      oneLiner: '长度、重量、温度、存储单位互转。',
      description: '单位换算工具，覆盖长度、重量、温度、数据存储与时间等常用单位，转换精确。',
      icon: 'bi-rulers',
      keywords: ['单位换算', '温度转换', '存储单位'],
      tier: 'P0',
      legacyPath: '/tools/code/unit-converter.html',
    },
    {
      slug: 'rmb-uppercase',
      name: '人民币大写转换',
      oneLiner: '金额数字转中文大写，财务单据可用。',
      description: '人民币金额大写转换工具，数字金额转换为中文大写，支持角分与负数处理。',
      icon: 'bi-currency-yen',
      keywords: ['人民币大写', '金额大写', '大写转换'],
      tier: 'P1',
      legacyPath: '/tools/life/rmb-uppercase.html',
    },
    {
      slug: 'fuel',
      name: '油耗计算器',
      oneLiner: '根据里程与油费计算百公里油耗。',
      description: '车辆油耗计算器，输入加油金额、油价与行驶里程，计算百公里油耗与每公里成本。',
      icon: 'bi-fuel-pump',
      keywords: ['油耗计算', '百公里油耗', '汽车油耗'],
      tier: 'P1',
      legacyPath: '/tools/life/fuel-consumption.html',
    },
    {
      slug: 'expiry',
      name: '保质期计算',
      oneLiner: '生产日期加保质期，到期日一目了然。',
      description: '保质期计算工具，输入生产日期与保质期天数，自动计算到期日期并给出剩余天数。',
      icon: 'bi-calendar-x',
      keywords: ['保质期计算', '到期日', '过期提醒'],
      tier: 'P1',
      legacyPath: '/tools/time/expiry-calculator.html',
    },
    {
      slug: 'keyboard-test',
      name: '键盘按键测试',
      oneLiner: '按下任意键，检测按键是否正常触发。',
      description: '键盘按键测试工具，实时显示按键名称与编码，快速排查键盘故障。',
      icon: 'bi-keyboard',
      keywords: ['键盘测试', '按键测试', '键盘检测'],
      tier: 'P0',
      legacyPath: '/tools/life/keyboard-test.html',
    },
    {
      slug: 'grid-splitter',
      name: '九宫格切图',
      oneLiner: '一张图切成九宫格，朋友圈排版神器。',
      description: '九宫格切图工具，把一张图片按 3x3 网格切分并导出，朋友圈与社交媒体排版利器。',
      icon: 'bi-grid-3x3-gap',
      keywords: ['九宫格切图', '朋友圈切图', '图片切分'],
      tier: 'P0',
      legacyPath: '/tools/life/grid-splitter.html',
    },
    {
      slug: 'sensitive-check',
      name: '敏感词检测',
      oneLiner: '文本扫描敏感词，支持自定义词库。',
      description: '敏感词检测工具，内置常用词库并支持自定义添加，命中位置高亮显示。',
      icon: 'bi-shield',
      keywords: ['敏感词检测', '敏感词过滤', '文本审核'],
      tier: 'P1',
      legacyPath: '/tools/text/sensitive-check.html',
    },
    {
      slug: 'zodiac',
      name: '生肖星座查询',
      oneLiner: '日期查生肖、星座与五行属性。',
      description: '生肖星座查询工具，输入出生日期查询生肖、星座、五行与守护信息。',
      icon: 'bi-star',
      keywords: ['生肖查询', '星座查询', '五行'],
      tier: 'P1',
      legacyPath: '/tools/time/zodiac.html',
    },
  ],
  fun: [
    {
      slug: 'ascii-art',
      name: 'ASCII 艺术字',
      oneLiner: '文字转 ASCII 艺术字，支持多种字体。',
      description: 'ASCII 艺术字生成器，输入文字生成大字 Banner 效果，支持多种风格字体。',
      icon: 'bi-emoji-sunglasses',
      keywords: ['ascii艺术字', 'ascii art', '字符画'],
      tier: 'P0',
      legacyPath: '/tools/code/ascii-art.html',
    },
    {
      slug: 'click-speed',
      name: '点击速度测试',
      oneLiner: '10 秒手速挑战，测测你的 APM。',
      description: '点击速度测试工具，10 秒内看你能点多少下，挑战你的手速极限。',
      icon: 'bi-cursor',
      keywords: ['点击测试', '手速测试', '鼠标点击'],
      tier: 'P0',
      legacyPath: '/tools/other/click-speed.html',
    },
    {
      slug: 'reaction-test',
      name: '反应力测试',
      oneLiner: '看谁反应快，测量你的反应时间。',
      description: '反应力测试工具，等待颜色变化后尽快点击，测量你的反应时间毫秒值。',
      icon: 'bi-lightning-charge',
      keywords: ['反应力测试', '反应速度', '反应时间'],
      tier: 'P1',
      legacyPath: '/tools/other/reaction-test.html',
    },
    {
      slug: 'lottery',
      name: '抽奖转盘',
      oneLiner: '自定义名单与奖项，滚动抽奖公平随机。',
      description: '年会抽奖工具，支持导入名单、设置奖项数量，滚动抽奖结果公平随机。',
      icon: 'bi-gift',
      keywords: ['抽奖工具', '年会抽奖', '转盘抽奖'],
      tier: 'P0',
      legacyPath: '/tools/life/lottery.html',
    },
    {
      slug: 'meme-generator',
      name: '表情包生成',
      oneLiner: '上传图片加文字，自定义表情包。',
      description: '表情包生成器，上传本地图片添加上下文字，支持字体与颜色调整后下载。',
      icon: 'bi-image-alt',
      keywords: ['表情包生成', 'meme', '图片加字'],
      tier: 'P1',
      legacyPath: '/tools/image/meme-generator.html',
    },
    {
      slug: 'nickname-text',
      name: '个性昵称创意文字',
      oneLiner: '火星文、花体、斜体、空心体等 20+ 风格一键生成个性昵称。',
      description: '个性昵称创意文字生成器：火星文、花体（Script）、斜体、粗体、空心体（Double-Struck）、德文花体（Fraktur）、无衬线、等宽、圈字、括号圈、方块圈、反白圈、上下标、全角、镜像等 20 余种 Unicode 风格一键转换。游戏昵称、情侣网名、QQ网名、微信网名、非主流个性签名都能生成，即开即用，纯浏览器本地生成。',
      icon: 'bi-stars',
      keywords: ['个性昵称', '花体字', '火星文', '游戏昵称', '情侣网名', '非主流网名'],
      tier: 'P1',
      legacyPath: '/tools/text/mars-text.html',
      legacyAliases: ['/tools/fun/fancy-text/'],
    },
    {
      slug: 'random-number',
      name: '随机数生成',
      oneLiner: '自定义范围与数量，真随机抽取。',
      description: '随机数生成工具，自定义最小值、最大值与数量，支持去重抽取。',
      icon: 'bi-shuffle',
      keywords: ['随机数', '随机数生成', '抽签'],
      tier: 'P0',
      legacyPath: '/tools/math/random.html',
    },
    {
      slug: 'palette-generator',
      name: '色板生成器',
      oneLiner: '一键生成和谐配色方案，一键复制。',
      description: '色板生成器，基于色彩理论自动生成和谐配色方案，支持复制与导出。',
      icon: 'bi-palette2',
      keywords: ['色板生成', '配色方案', '色彩搭配'],
      tier: 'P1',
      legacyPath: '/tools/image/palette-generator.html',
    },
    {
      slug: 'browser-info',
      name: '浏览器信息检测',
      oneLiner: '查看浏览器、屏幕与系统信息。',
      description: '浏览器信息检测工具，展示浏览器版本、操作系统、屏幕分辨率与设备信息。',
      icon: 'bi-browser-chrome',
      keywords: ['浏览器信息', '浏览器检测', '屏幕分辨率'],
      tier: 'P0',
      legacyPath: '/tools/code/browser-info.html',
    },
    {
      slug: 'image-filter',
      name: '图片滤镜',
      oneLiner: '灰度、模糊、复古等滤镜一键应用。',
      description: '图片滤镜工具，上传图片应用灰度、模糊、复古、色相旋转等滤镜效果并下载。',
      icon: 'bi-brush',
      keywords: ['图片滤镜', '照片滤镜', '滤镜'],
      tier: 'P1',
      legacyPath: '/tools/image/image-filter.html',
    },
    {
      slug: 'morse',
      name: '摩斯密码',
      oneLiner: '文字与摩斯电码互转，附字母表。',
      description: '摩斯密码编解码工具，支持中英文与数字，实时翻译并附摩斯电码表。',
      icon: 'bi-broadcast',
      keywords: ['摩斯密码', '摩斯电码', 'morse'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/morse.html',
    },
  ],
};

export function getToolHref(category: ToolCategory, slug: string): string {
  return `/tools/${category}/${slug}/`;
}

export function getAllTools(): (ToolMeta & { category: ToolCategory })[] {
  return (Object.keys(TOOLS) as ToolCategory[]).flatMap((category) =>
    TOOLS[category].map((tool) => ({ ...tool, category })),
  );
}
