export type ToolCategory = 'dev' | 'daily' | 'fun';

export interface ToolMeta {
  slug: string;
  name: string;
  oneLiner: string;
  description: string;
  icon: string;
  keywords: string[];
  tier: 'P0' | 'P1';
  worker?: boolean;
  legacyPath?: string;
}

export interface CategoryMeta {
  id: ToolCategory;
  name: string;
  icon: string;
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'dev',
    name: '开发实用',
    icon: 'bi-code-square',
    blurb: '编码、格式化、加解密与调试，开发日常高频刚需。',
  },
  {
    id: 'daily',
    name: '日常实用',
    icon: 'bi-house-heart',
    blurb: '日期、理财、换算与效率小工具，生活工作两相宜。',
  },
  {
    id: 'fun',
    name: '趣味工具',
    icon: 'bi-emoji-sunglasses',
    blurb: '减压、娱乐与创意小玩意，给忙碌的日常加点乐趣。',
  },
];

export const TOOLS: Record<ToolCategory, ToolMeta[]> = {
  dev: [
    {
      slug: 'json-formatter',
      name: 'JSON 格式化与校验',
      oneLiner: '格式化、压缩、校验 JSON，实时定位语法错误。',
      description: '在线 JSON 格式化与校验工具，粘贴自动美化或压缩，语法错误实时定位行号，支持缩进自定义，纯浏览器处理数据不出本地。',
      icon: 'bi-braces',
      keywords: ['json格式化', 'json校验', 'json压缩'],
      tier: 'P0',
      legacyPath: '/tools/code/json-compress.html',
    },
    {
      slug: 'json-convert',
      name: 'JSON 转 CSV/Excel',
      oneLiner: '一键把 JSON 数组转为 CSV 或 Excel 表格。',
      description: '在线 JSON 转 CSV/Excel 表格工具，把 JSON 数组一键转为表格文件，支持表头定制与下载，纯浏览器处理，接口数据导出更方便。',
      icon: 'bi-table',
      keywords: ['json转csv', 'json转excel', 'json转表格'],
      tier: 'P0',
      legacyPath: '/tools/code/json2csv.html',
    },
    {
      slug: 'json-codegen',
      name: 'JSON 转实体类',
      oneLiner: '从 JSON 生成 TypeScript、Go、Java、C# 类型定义。',
      description: '在线 JSON 转实体类工具，根据 JSON 示例生成 TypeScript、Go、Java、C# 类型定义，减少手写代码，前后端联调对齐数据结构。',
      icon: 'bi-file-code',
      keywords: ['json转ts', 'json转go', 'json转java', 'json转csharp'],
      tier: 'P1',
      legacyPath: '/tools/code/json2ts.html',
    },
    {
      slug: 'json-xml-yaml',
      name: 'JSON/XML/YAML 互转',
      oneLiner: '三种数据格式无损互转，保留结构层次。',
      description: '在线 JSON/XML/YAML 互转工具，三种数据格式无损转换，保留结构层次，支持缩进配置，适合接口数据迁移与配置文件处理。',
      icon: 'bi-arrow-left-right',
      keywords: ['json转xml', 'json转yaml', 'xml转json', 'yaml转json'],
      tier: 'P0',
      legacyPath: '/tools/json/xml.html',
    },
    {
      slug: 'jsonpath',
      name: 'JSONPath 查询',
      oneLiner: '用 JSONPath 表达式从 JSON 中提取数据。',
      description: '在线 JSONPath 查询工具，输入 JSON 与表达式实时高亮匹配结果，支持常见语法与过滤条件，接口调试与数据提取更高效。',
      icon: 'bi-signpost-split',
      keywords: ['jsonpath', 'json查询', 'jsonpath解析'],
      tier: 'P1',
      legacyPath: '/tools/code/jsonpath.html',
    },
    {
      slug: 'diff',
      name: '文本差异对比',
      oneLiner: '逐行对比两段文本，差异高亮一目了然。',
      description: '在线文本差异对比工具，两段文本逐行比较，行内高亮增删改并统计数量，适合配置、代码与 JSON 内容快速比对。',
      icon: 'bi-file-diff',
      keywords: ['文本对比', 'diff', '代码对比', 'json对比'],
      tier: 'P0',
      legacyPath: '/tools/text/diff.html',
    },
    {
      slug: 'base64',
      name: 'Base64 编解码',
      oneLiner: '文本与 Base64 互转，支持图片数据转码。',
      description: '在线 Base64 编解码工具，支持 UTF-8 中文、URL 安全模式与图片转 Base64，编码解码在浏览器本地完成，数据不泄露。',
      icon: 'bi-code-square',
      keywords: ['base64', 'base64编码', 'base64解码'],
      tier: 'P0',
      legacyPath: '/tools/code/base64.html',
    },
    {
      slug: 'url-encode',
      name: 'URL 编解码',
      oneLiner: 'URL 编码、解码与参数还原，中文不乱码。',
      description: '在线 URL 编解码工具，正确处理中文与特殊字符，支持完整组件与查询参数两种模式，接口调用与前端调试更方便。',
      icon: 'bi-link-45deg',
      keywords: ['url编码', 'url解码', 'urlencode'],
      tier: 'P0',
      legacyPath: '/tools/code/url.html',
    },
    {
      slug: 'html-formatter',
      name: 'HTML 格式化与实体转换',
      oneLiner: 'HTML 美化压缩，标签实体编码解码。',
      description: '在线 HTML 格式化工具，支持压缩与 HTML 实体编码解码，适合邮件模板、富文本内容处理，粘贴源码一键整理。',
      icon: 'bi-filetype-html',
      keywords: ['html格式化', 'html压缩', 'html实体编码'],
      tier: 'P0',
      legacyPath: '/tools/code/html-formatter.html',
    },
    {
      slug: 'css-formatter',
      name: 'CSS 格式化与单位换算',
      oneLiner: 'CSS 美化压缩，px/rem/em/vw 实时互转。',
      description: '在线 CSS 格式化与压缩工具，附带 px、rem、em、vw 单位换算，前端开发调整样式与移动端适配更顺手。',
      icon: 'bi-filetype-css',
      keywords: ['css格式化', 'css压缩', 'css单位换算'],
      tier: 'P0',
      legacyPath: '/tools/code/css.html',
    },
    {
      slug: 'js-formatter',
      name: 'JavaScript 格式化',
      oneLiner: 'JS 代码美化与压缩，兼容现代语法。',
      description: '在线 JavaScript 格式化工具，支持 ES 现代语法与常用配置项，粘贴即可整理缩进与分号，代码更清晰易读。',
      icon: 'bi-filetype-js',
      keywords: ['javascript格式化', 'js压缩', 'js美化'],
      tier: 'P0',
      legacyPath: '/tools/code/javascript.html',
    },
    {
      slug: 'sql-formatter',
      name: 'SQL 格式化',
      oneLiner: 'SQL 语句美化缩进，支持多种方言。',
      description: '在线 SQL 格式化工具，支持 MySQL、PostgreSQL、SQL Server 等方言，冗长语句整理为层次清晰的结构。',
      icon: 'bi-database',
      keywords: ['sql格式化', 'sql美化', 'sql缩进'],
      tier: 'P1',
      legacyPath: '/tools/code/sql-formatter.html',
    },
    {
      slug: 'xml-formatter',
      name: 'XML 格式化与压缩',
      oneLiner: 'XML 美化、压缩与合法性校验。',
      description: '在线 XML 格式化与压缩工具，附带结构校验与错误提示，适合接口报文与配置文件处理，快速定位标签问题。',
      icon: 'bi-filetype-xml',
      keywords: ['xml格式化', 'xml压缩', 'xml校验'],
      tier: 'P0',
      legacyPath: '/tools/code/xml-format.html',
    },
    {
      slug: 'markdown',
      name: 'Markdown 在线编辑器',
      oneLiner: '工具栏、快捷键、实时预览，写作排版所见即所得。',
      description: '在线 Markdown 编辑器，工具栏快捷语法、分屏实时预览、目录大纲、复制富文本，草稿自动保存，支持导出 Markdown/HTML。',
      icon: 'bi-markdown',
      keywords: ['markdown编辑器', 'markdown在线', 'markdown预览', 'markdown转html'],
      tier: 'P0',
      legacyPath: '/tools/code/markdown.html',
    },
    {
      slug: 'regex-tester',
      name: '正则表达式测试',
      oneLiner: '实时匹配高亮，附带常用表达式库。',
      description: '在线正则表达式测试器，输入表达式与待匹配文本，实时高亮结果并展示捕获组，内置常用正则示例库，支持替换预览，复杂表达式调试更直观。',
      icon: 'bi-asterisk',
      keywords: ['正则测试', '正则表达式', 'regex'],
      tier: 'P0',
      legacyPath: '/tools/code/regex-tester.html',
    },
    {
      slug: 'text-transform',
      name: '文本转换工具',
      oneLiner: '大小写、驼峰下划线、全角半角一键互转。',
      description: '在线文本转换工具，大小写、驼峰下划线、全角半角一键互转，批量处理粘贴即用，变量命名与文案整理更方便。',
      icon: 'bi-textarea-t',
      keywords: ['大小写转换', '驼峰转换', '全角半角', '下划线转驼峰'],
      tier: 'P0',
      legacyPath: '/tools/text/case.html',
    },
    {
      slug: 'text-toolbox',
      name: '文本处理工具',
      oneLiner: '去重、排序、反转、去除空行，批量清洗。',
      description: '在线文本处理工具箱，按行去重、排序、反转、去除空行、统计行数，适合日志与列表数据快速清洗，纯浏览器处理。',
      icon: 'bi-list-check',
      keywords: ['文本去重', '文本排序', '去除空行', '文本反转'],
      tier: 'P1',
      legacyPath: '/tools/text/dedupe.html',
    },
    {
      slug: 'jianfan',
      name: '简繁转换',
      oneLiner: '简体繁体互转，保留用词习惯。',
      description: '在线简体繁体转换工具，简繁一键互转，轻量引擎本地即时转换，文档本地化与繁体阅读更轻松。',
      icon: 'bi-arrow-repeat',
      keywords: ['简繁转换', '繁体转简体', '简体转繁体'],
      tier: 'P0',
      legacyPath: '/tools/text/jianfan.html',
    },
    {
      slug: 'pinyin',
      name: '汉字转拼音',
      oneLiner: '中文转拼音，支持声调与首字母模式。',
      description: '在线汉字转拼音工具，支持全拼、带声调与首字母三种输出，多音字按语境自动选音，可用于搜索索引、URL 生成与姓名转换，结果可批量复制。',
      icon: 'bi-translate',
      keywords: ['汉字转拼音', '拼音转换', '中文拼音'],
      tier: 'P1',
      legacyPath: '/tools/text/pinyin.html',
    },
    {
      slug: 'cron',
      name: 'Cron 表达式工具',
      oneLiner: '解析表达式，预览未来执行时间。',
      description: '在线 Cron 表达式工具，解析与生成定时任务表达式，实时展示下次执行时间与调度日历，支持 5/6/7 段格式。',
      icon: 'bi-calendar2-week',
      keywords: ['cron表达式', 'cron解析', '定时任务'],
      tier: 'P0',
      legacyPath: '/tools/code/cron-parser.html',
    },
    {
      slug: 'base-converter',
      name: '进制转换',
      oneLiner: '二进制、八进制、十进制、十六进制互转。',
      description: '在线进制转换工具，支持二进制、八进制、十进制、十六进制互转与补码表示，附带位宽与有符号选项，输入即时换算，编程与网络学习更顺手。',
      icon: 'bi-123',
      keywords: ['进制转换', '二进制转十六进制', '十六进制'],
      tier: 'P0',
      legacyPath: '/tools/dev-tools/base-converter.html',
    },
    {
      slug: 'unicode-converter',
      name: 'Unicode/ASCII 转换',
      oneLiner: '字符与 \\uXXXX 转义互转，ASCII 码表速查。',
      description: '在线 Unicode/ASCII 转换工具，中文转 \\u 编码、ASCII 码表查询与字符互转，适合 JSON 转义与编码调试。',
      icon: 'bi-fonts',
      keywords: ['unicode转换', 'ascii码', '\\u编码'],
      tier: 'P1',
      legacyPath: '/tools/code/unicode-converter.html',
    },
    {
      slug: 'hash',
      name: 'Hash 生成器',
      oneLiner: 'MD5、SHA 系列、Keccak 与文件哈希计算。',
      description: '在线 Hash 计算工具，支持 MD5、SHA-1、SHA-256、SHA-512、Keccak 与文件哈希，全部浏览器本地完成，文件不上传。',
      icon: 'bi-fingerprint',
      keywords: ['md5加密', 'sha256', '文件哈希', 'hash计算'],
      tier: 'P0',
      legacyPath: '/tools/format-conversion/hash-generator.html',
    },
    {
      slug: 'symmetric-encrypt',
      name: '对称加密工具',
      oneLiner: 'AES、DES、RC4、Rabbit 加解密，浏览器内完成。',
      description: '在线对称加密工具，AES、DES、RC4、Rabbit 加解密，支持多种填充模式与输出格式，本地验证加解密流程。',
      icon: 'bi-lock',
      keywords: ['aes加密', 'des加密', 'rc4加密', '对称加密'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/aes.html',
    },
    {
      slug: 'rsa-encrypt',
      name: 'RSA 加解密',
      oneLiner: '密钥生成、加密、解密、签名一站式。',
      description: '在线 RSA 加解密工具，密钥对生成、加解密、签名验签与 PEM 导入导出，浏览器本地完成，理解非对称加密原理。',
      icon: 'bi-key',
      keywords: ['rsa加密', 'rsa解密', 'rsa密钥生成'],
      tier: 'P1',
      legacyPath: '/tools/encrypt/rsa.html',
    },
    {
      slug: 'bcrypt',
      name: 'Bcrypt 校验',
      oneLiner: '生成 Bcrypt 哈希并校验密码。',
      description: '在线 Bcrypt 密码哈希工具，生成与校验密码哈希，支持自定义 cost 轮数，浏览器本地计算，常用于后端密码存储验证。',
      icon: 'bi-shield-check',
      keywords: ['bcrypt', 'bcrypt加密', 'bcrypt校验'],
      tier: 'P1',
      legacyPath: '/tools/encrypt/bcrypt.html',
    },
    {
      slug: 'jwt-decoder',
      name: 'JWT 解码器',
      oneLiner: '解析 JWT 三段结构，Payload 一目了然。',
      description: '在线 JWT 解码工具，解析 Header 与 Payload 并美化展示，支持 HS256 签名验签，调试登录态与接口鉴权更方便。',
      icon: 'bi-file-lock',
      keywords: ['jwt解码', 'jwt解析', 'token解析'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/jwt.html',
    },
    {
      slug: 'password-strength',
      name: '密码强度检测',
      oneLiner: '实时评估密码强度，指出薄弱点。',
      description: '在线密码强度检测工具，从长度、字符组合、常见弱密码库等多维度评分，给出具体改进建议与修改方向，检测全程在浏览器本地完成，密码不上传。',
      icon: 'bi-shield-exclamation',
      keywords: ['密码强度', '密码检测', '密码安全'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/password-strength.html',
    },
    {
      slug: 'password-generator',
      name: '随机密码生成',
      oneLiner: '按规则生成高强度随机密码。',
      description: '在线随机密码生成器，可自定义长度与字符集，基于密码学安全随机源生成强密码，支持排除易混淆字符与批量生成多条，一键复制。',
      icon: 'bi-dice-5',
      keywords: ['密码生成', '随机密码', '强密码'],
      tier: 'P0',
      legacyPath: '/tools/code/password-generator.html',
    },
    {
      slug: 'uuid-generator',
      name: 'UUID/NanoID 生成',
      oneLiner: '批量生成 UUID v4/v7 与 NanoID。',
      description: '在线 UUID/NanoID 生成工具，UUID v4、v7 与 NanoID 批量生成，支持数量、大小写与分隔符设置，即开即用。',
      icon: 'bi-hash',
      keywords: ['uuid生成', 'nanoid', 'uuid'],
      tier: 'P0',
      legacyPath: '/tools/dev-tools/uuid-generator.html',
    },
    {
      slug: 'qrcode',
      name: '二维码/条形码生成',
      oneLiner: '文本转二维码或条形码，支持配色下载。',
      description: '在线二维码/条形码生成器，支持容错级别、颜色定制与 PNG 下载，生成链接、文本、WiFi 等二维码，浏览器本地生成。',
      icon: 'bi-qr-code',
      keywords: ['二维码生成', '条形码生成', 'qr码'],
      tier: 'P0',
      legacyPath: '/tools/image/qrcode-generator.html',
    },
    {
      slug: 'http-tester',
      name: 'HTTP 接口测试',
      oneLiner: '构造请求调试接口，查看响应与耗时。',
      description: '在线 HTTP 接口测试工具，支持常用方法、请求头与 Body 配置，实时展示状态码、响应头与耗时，免安装调试接口。',
      icon: 'bi-send',
      keywords: ['http测试', '接口测试', 'api测试'],
      tier: 'P0',
      legacyPath: '/tools/network/api-tester.html',
    },
    {
      slug: 'ip-lookup',
      name: 'IP 地址查询',
      oneLiner: 'IPv4/IPv6 深度解析，查询归属地、运营商与网段信息。',
      description: '在线 IP 地址查询工具，本机 IP 与任意 IPv4/IPv6 查询，展示属地、运营商与经纬度，附带 CIDR 网段与进制计算。',
      icon: 'bi-globe2',
      keywords: ['ip查询', 'ip归属地', 'ip地址查询', 'ipv6', '域名解析', 'ip解析'],
      tier: 'P0',
      worker: true,
      legacyPath: '/tools/network/ip-lookup.html',
    },
    {
      slug: 'ua-parser',
      name: 'User-Agent 解析',
      oneLiner: '解析 UA 串，识别浏览器、系统与设备。',
      description: '在线 User-Agent 解析工具，从 UA 字符串识别浏览器、操作系统与设备类型，排查访问日志与客户端环境更高效。',
      icon: 'bi-pc-display',
      keywords: ['ua解析', 'user-agent', '浏览器识别'],
      tier: 'P1',
      legacyPath: '/tools/code/ua-parser.html',
    },
    {
      slug: 'url-parse',
      name: 'URL 参数解析',
      oneLiner: '拆分 URL 各组件，参数表格化展示。',
      description: '在线 URL 参数解析工具，拆分协议、域名、路径、查询参数与锚点，参数表格化展示，前端调试与抓包分析更顺手。',
      icon: 'bi-diagram-3',
      keywords: ['url解析', 'url参数', '链接参数'],
      tier: 'P0',
      legacyPath: '/tools/network/url-parse.html',
    },
    {
      slug: 'color-convert',
      name: '颜色转换与取色',
      oneLiner: 'HEX、RGB、HSL 互转，取色器实时预览。',
      description: '在线颜色转换工具，HEX、RGB、HSL 互转与屏幕取色，实时预览色值与对比度，设计还原与前端配色更高效。',
      icon: 'bi-palette',
      keywords: ['颜色转换', 'hex转rgb', '取色器'],
      tier: 'P0',
      legacyPath: '/tools/format-conversion/color-converter.html',
    },
    {
      slug: 'image-to-base64',
      name: '图片转 Base64',
      oneLiner: '图片文件转 Base64，用于内联与传输。',
      description: '在线图片转 Base64 工具，本地图片直接转换，支持压缩选项与多种输出格式，方便嵌入代码与接口报文。',
      icon: 'bi-image',
      keywords: ['图片转base64', '图片base64', 'base64图片'],
      tier: 'P1',
      legacyPath: '/tools/format-conversion/img2base64.html',
    },
  ],
  daily: [
    {
      slug: 'calendar',
      name: '在线万年历',
      oneLiner: '公历农历对照、节气和节假日查询。',
      description: '在线万年历，公历农历对照展示，支持二十四节气、法定节假日与黄历宜忌查询，点击日期查看当日生肖星座五行。',
      icon: 'bi-calendar3',
      keywords: ['万年历', '农历', '节气'],
      tier: 'P0',
      legacyPath: '/tools/time/calendar.html',
    },
    {
      slug: 'lunar-converter',
      name: '公历农历互转',
      oneLiner: '公历与农历日期双向转换。',
      description: '在线公历农历互转工具，支持农历闰月与节气标注，可快速换算生日、纪念日与节日的农历日期，转换在浏览器本地即时完成。',
      icon: 'bi-moon-stars',
      keywords: ['公历转农历', '农历转公历', '农历查询'],
      tier: 'P0',
      legacyPath: '/tools/time/lunar-solar-converter.html',
    },
    {
      slug: 'world-clock',
      name: '世界时钟',
      oneLiner: '全球多时区时间对照与转换。',
      description: '在线世界时钟与时区转换工具，多城市时间对照、任意时区换算与时差计算，跨国会议、出差协作与远程办公排期更清晰。',
      icon: 'bi-globe-americas',
      keywords: ['世界时钟', '时区转换', '多时区'],
      tier: 'P0',
      legacyPath: '/tools/time/world.html',
    },
    {
      slug: 'date-diff',
      name: '日期间隔计算',
      oneLiner: '两个日期相差天数，含周数与日历月换算。',
      description: '在线日期间隔计算工具，计算两个日期相差的天数、周数与月数，支持日期加减指定天数并实时刷新，合同期限、项目排期与倒计时规划更准确。',
      icon: 'bi-hourglass-split',
      keywords: ['日期间隔', '日期计算', '相差天数'],
      tier: 'P0',
      legacyPath: '/tools/time/interval.html',
    },
    {
      slug: 'timestamp',
      name: '时间戳转换',
      oneLiner: '秒/毫秒时间戳与日期实时互转。',
      description: '在线时间戳转换工具，Unix 时间戳与日期时间互转，自动识别秒与毫秒，支持实时时钟与批量转换，联调排查更方便。',
      icon: 'bi-clock-history',
      keywords: ['时间戳转换', 'unix时间戳', '时间戳在线'],
      tier: 'P0',
      legacyPath: '/tools/time/timestamp.html',
    },
    {
      slug: 'workday',
      name: '工作日计算器',
      oneLiner: '计算两个日期之间的工作日天数。',
      description: '在线工作日计算器，排除周末与法定节假日，统计日期区间实际工作日并处理调休，考勤排班与工期计算更准确。',
      icon: 'bi-briefcase',
      keywords: ['工作日计算', '工作日天数', '考勤计算'],
      tier: 'P1',
      legacyPath: '/tools/time/workday-calculator.html',
    },
    {
      slug: 'age-calculator',
      name: '年龄计算器',
      oneLiner: '精确到天与时刻的年龄计算。',
      description: '在线年龄计算器，从出生日期精确计算周岁、虚岁与出生天数，自动判断是否已过生日，实时更新结果，办证登记与日常查询都方便。',
      icon: 'bi-person',
      keywords: ['年龄计算', '周岁', '出生天数'],
      tier: 'P1',
      legacyPath: '/tools/time/age.html',
    },
    {
      slug: 'timer',
      name: '倒计时与秒表',
      oneLiner: '在线倒计时与秒表，专注计时两不误。',
      description: '在线倒计时与秒表工具，支持自定义时长、开始暂停重置与结束时提醒，可连续多次计时，适合专注工作、运动训练与活动倒计时。',
      icon: 'bi-stopwatch',
      keywords: ['倒计时', '秒表', '计时器'],
      tier: 'P0',
      legacyPath: '/tools/time/countdown.html',
    },
    {
      slug: 'bmi',
      name: 'BMI 计算器',
      oneLiner: '身高体重算 BMI，附健康区间参考。',
      description: '在线 BMI 体重指数计算器，根据身高体重计算指数并对照健康区间，附带标准体重范围建议，支持单位切换，帮助了解自身体重状况。',
      icon: 'bi-heart-pulse',
      keywords: ['bmi计算', '体重指数', '健康指数'],
      tier: 'P0',
      legacyPath: '/tools/life/bmi-calculator.html',
    },
    {
      slug: 'salary',
      name: '工资与五险一金计算',
      oneLiner: '税前税后工资与五险一金明细计算。',
      description: '在线税后工资计算器，包含五险一金与个税明细，按城市比例配置，支持专项附加扣除，税前税后换算，收入构成一目了然。',
      icon: 'bi-cash-stack',
      keywords: ['税后工资', '五险一金', '工资计算器'],
      tier: 'P0',
      legacyPath: '/tools/life/salary.html',
    },
    {
      slug: 'finance',
      name: '理财计算器',
      oneLiner: '贷款、复利与百分比计算汇总。',
      description: '在线理财计算器，支持贷款月供、等额本息、复利收益与百分比计算，输入参数即得参考结果，购房贷款与理财收益测算更方便。',
      icon: 'bi-percent',
      keywords: ['贷款计算', '复利计算', '百分比计算'],
      tier: 'P1',
      legacyPath: '/tools/math/loan-calculator.html',
    },
    {
      slug: 'calculator',
      name: '多功能计算器',
      oneLiner: '标准与科学计算一体，常用函数齐全。',
      description: '在线多功能计算器，支持四则混合运算、阶乘、幂、开方、质数判定与数列求和，附带常用常数，满足日常计算与学习需求。',
      icon: 'bi-calculator',
      keywords: ['计算器', '科学计算器', '数学计算'],
      tier: 'P0',
      legacyPath: '/tools/math/calculator.html',
    },
    {
      slug: 'unit-converter',
      name: '单位换算',
      oneLiner: '长度、重量、温度、存储单位互转。',
      description: '在线单位换算工具，覆盖长度、重量、温度、数据存储、时间与面积等常用单位，转换精确即时，学习、设计与数据处理更方便。',
      icon: 'bi-rulers',
      keywords: ['单位换算', '温度转换', '存储单位'],
      tier: 'P0',
      legacyPath: '/tools/code/unit-converter.html',
    },
    {
      slug: 'rmb-uppercase',
      name: '人民币大写转换',
      oneLiner: '金额数字转中文大写，财务单据可用。',
      description: '在线人民币大写转换工具，数字金额一键转中文大写，支持角分、负数与金额校验，财务单据、合同与报销凭证填写更规范。',
      icon: 'bi-currency-yen',
      keywords: ['人民币大写', '金额大写', '大写转换'],
      tier: 'P1',
      legacyPath: '/tools/life/rmb-uppercase.html',
    },
    {
      slug: 'fuel',
      name: '油耗计算器',
      oneLiner: '根据里程与油费计算百公里油耗。',
      description: '在线车辆油耗计算器，输入加油金额、油价与行驶里程，自动计算百公里油耗与每公里成本，支持多次记录对比，了解油耗水平与出行开销。',
      icon: 'bi-fuel-pump',
      keywords: ['油耗计算', '百公里油耗', '汽车油耗'],
      tier: 'P1',
      legacyPath: '/tools/life/fuel-consumption.html',
    },
    {
      slug: 'expiry',
      name: '保质期计算',
      oneLiner: '生产日期加保质期，到期日一目了然。',
      description: '在线保质期计算工具，输入生产日期与保质期天数或到期日期，自动计算到期日与剩余天数，临期自动提醒，食品药品效期管理更省心。',
      icon: 'bi-calendar-x',
      keywords: ['保质期计算', '到期日', '过期提醒'],
      tier: 'P1',
      legacyPath: '/tools/time/expiry-calculator.html',
    },
    {
      slug: 'keyboard-test',
      name: '键盘按键测试',
      oneLiner: '按下任意键，检测按键是否正常触发。',
      description: '在线键盘按键测试工具，实时显示按键名称、编码与状态，支持组合键与多键同按检测，快速排查键盘故障与按键冲突问题。',
      icon: 'bi-keyboard',
      keywords: ['键盘测试', '按键测试', '键盘检测'],
      tier: 'P0',
      legacyPath: '/tools/life/keyboard-test.html',
    },
    {
      slug: 'grid-splitter',
      name: '九宫格切图',
      oneLiner: '一张图切成九宫格，朋友圈排版神器。',
      description: '在线九宫格切图工具，把一张图片按 3x3 网格切分并导出，朋友圈九宫格与社交媒体排版利器，图片本地处理。',
      icon: 'bi-grid-3x3-gap',
      keywords: ['九宫格切图', '朋友圈切图', '图片切分'],
      tier: 'P0',
      legacyPath: '/tools/life/grid-splitter.html',
    },
    {
      slug: 'sensitive-check',
      name: '敏感词检测',
      oneLiner: '文本扫描敏感词，支持自定义词库。',
      description: '在线敏感词检测工具，内置常用词库并支持自定义添加与管理，命中位置高亮并统计次数，内容发布前自查与文本审核更放心。',
      icon: 'bi-shield',
      keywords: ['敏感词检测', '敏感词过滤', '文本审核'],
      tier: 'P1',
      legacyPath: '/tools/text/sensitive-check.html',
    },
    {
      slug: 'zodiac',
      name: '生肖星座查询',
      oneLiner: '日期查生肖、星座与五行属性。',
      description: '在线生肖星座查询工具，输入出生日期查询生肖、星座、五行与守护信息，附带年份生肖对照表，趣味查询与资料填写更方便。',
      icon: 'bi-star',
      keywords: ['生肖查询', '星座查询', '五行'],
      tier: 'P1',
      legacyPath: '/tools/time/zodiac.html',
    },
  ],
  fun: [
    {
      slug: 'ascii-art',
      name: 'ASCII 艺术字',
      oneLiner: '文字转 ASCII 艺术字，支持英文字体、中文像素画与图片转字符画。',
      description: 'ASCII 艺术字生成器：21 种 FIGlet 英文字体、中文/任意字符像素画、图片转字符画，支持 ANSI 终端彩色输出。',
      icon: 'bi-emoji-sunglasses',
      keywords: ['ascii艺术字', 'ascii art', '字符画', '中文字符画', '图片转ascii'],
      tier: 'P0',
      legacyPath: '/tools/code/ascii-art.html',
    },
    {
      slug: 'click-speed',
      name: '点击速度测试',
      oneLiner: '10 秒手速挑战，测测你的 APM。',
      description: '在线点击速度测试工具，10 秒手速挑战，实时统计点击次数与 APM 并给出评级，趣味比拼与鼠标手感测试。',
      icon: 'bi-cursor',
      keywords: ['点击测试', '手速测试', '鼠标点击'],
      tier: 'P0',
      legacyPath: '/tools/other/click-speed.html',
    },
    {
      slug: 'reaction-test',
      name: '反应力测试',
      oneLiner: '看谁反应快，测量你的反应时间。',
      description: '在线反应力测试工具，等待背景变色后尽快点击，精确测量反应时间毫秒值，支持多次测试取平均成绩与评级，趣味自测与反应训练。',
      icon: 'bi-lightning-charge',
      keywords: ['反应力测试', '反应速度', '反应时间'],
      tier: 'P1',
      legacyPath: '/tools/other/reaction-test.html',
    },
    {
      slug: 'schulte-trainer',
      name: '舒尔特训练',
      oneLiner: '经典方格与动态圆盘多模式，训练专注力与视觉搜索。',
      description: '舒尔特训练专区：经典方格、间隔随机变换、旋转多环圆盘与双圆盘、记忆方格、倒计时挑战与双任务干扰七种模式，难度可调，自动计时并生成完成时间、错点与趋势分析报告，通过主动视觉搜索对抗短视频造成的注意力碎片化。',
      icon: 'bi-bullseye',
      keywords: ['舒尔特', '舒尔特方格', '专注力训练', '注意力训练', '视觉搜索', '反应训练', '记忆训练'],
      tier: 'P1',
    },
    {
      slug: 'ball-tracker',
      name: '目标球追踪',
      oneLiner: '追踪目标球，克制诱惑与冲动，训练前额叶抑制控制。',
      description: '目标球追踪训练专区：目标追踪、干扰追踪与时机等待三种模式，在移动球群中持续锁定目标，抵御诱惑球与陷阱球干扰，克制提前点击的急躁冲动，生成追踪准确率、冲动误点与趋势分析报告，锻炼前额叶抑制控制与动态视觉追踪能力。',
      icon: 'bi-crosshair',
      keywords: ['目标追踪', '视觉追踪', '前额叶训练', '冲动控制', '抗干扰', '注意力训练'],
      tier: 'P1',
    },
    {
      slug: 'lottery',
      name: '抽奖转盘',
      oneLiner: '自定义名单与奖项，滚动抽奖公平随机。',
      description: '在线年会抽奖转盘，支持名单批量导入、奖项数量与中奖人数设置，转轮运动精确规划、停点公平随机，年会活动与课堂点名都适用。',
      icon: 'bi-gift',
      keywords: ['抽奖工具', '年会抽奖', '转盘抽奖'],
      tier: 'P0',
      legacyPath: '/tools/life/lottery.html',
    },
    {
      slug: 'meme-generator',
      name: '表情包生成',
      oneLiner: '上传图片加文字，自定义表情包。',
      description: '在线表情包生成器，上传本地图片添加上下文字，支持字体、字号与颜色调整，预览满意后下载，图片全程本地处理不上传。',
      icon: 'bi-image-alt',
      keywords: ['表情包生成', 'meme', '图片加字'],
      tier: 'P1',
      legacyPath: '/tools/image/meme-generator.html',
    },
    {
      slug: 'nickname-text',
      name: '个性昵称创意文字',
      oneLiner: '火星文、花体、斜体、空心体等 20+ 风格一键生成个性昵称。',
      description: '在线个性昵称生成器，火星文、花体、斜体、粗体、空心体等 20 余种 Unicode 风格一键转换，游戏昵称、情侣网名与个性签名都能生成。',
      icon: 'bi-stars',
      keywords: ['个性昵称', '花体字', '火星文', '游戏昵称', '情侣网名', '非主流网名'],
      tier: 'P1',
      legacyPath: '/tools/text/mars-text.html',
      legacyAliases: ['/tools/fun/fancy-text/'],
    },
    {
      slug: 'random-number',
      name: '随机数生成',
      oneLiner: '自定义范围与数量，真随机抽取。',
      description: '在线随机数生成工具，自定义范围与数量，支持去重抽取，抽签分组与测试数据生成更快捷，结果浏览器本地随机。',
      icon: 'bi-shuffle',
      keywords: ['随机数', '随机数生成', '抽签'],
      tier: 'P0',
      legacyPath: '/tools/math/random.html',
    },
    {
      slug: 'palette-generator',
      name: '色板生成器',
      oneLiner: '一键生成和谐配色方案，一键复制。',
      description: '在线色板生成器，基于色彩理论自动生成和谐配色方案，支持多套方案切换、色值一键复制与导出，设计选色与界面配色更高效。',
      icon: 'bi-palette2',
      keywords: ['色板生成', '配色方案', '色彩搭配'],
      tier: 'P1',
      legacyPath: '/tools/image/palette-generator.html',
    },
    {
      slug: 'browser-info',
      name: '浏览器信息检测',
      oneLiner: '查看浏览器、屏幕与系统信息。',
      description: '在线浏览器信息检测工具，展示浏览器版本、操作系统、屏幕分辨率与设备信息，兼容性排查与前端调试更方便。',
      icon: 'bi-browser-chrome',
      keywords: ['浏览器信息', '浏览器检测', '屏幕分辨率'],
      tier: 'P0',
      legacyPath: '/tools/code/browser-info.html',
    },
    {
      slug: 'image-filter',
      name: '图片滤镜',
      oneLiner: '灰度、模糊、复古等滤镜一键应用。',
      description: '在线图片滤镜工具，上传图片应用灰度、模糊、复古、色相旋转等滤镜效果，强度可调并实时预览，满意后下载，图片全程本地处理。',
      icon: 'bi-brush',
      keywords: ['图片滤镜', '照片滤镜', '滤镜'],
      tier: 'P1',
      legacyPath: '/tools/image/image-filter.html',
    },
    {
      slug: 'morse',
      name: '摩斯密码',
      oneLiner: '文字与摩斯电码互转，附字母表。',
      description: '在线摩斯密码编解码工具，支持中英文、数字与常用符号，实时翻译并附摩斯电码表，学习电码、趣味密文交流与通信演示更方便。',
      icon: 'bi-broadcast',
      keywords: ['摩斯密码', '摩斯电码', 'morse'],
      tier: 'P0',
      legacyPath: '/tools/encrypt/morse.html',
    },
  ],
};

export function getToolHref(category: ToolCategory, slug: string): string {
  return `/tools/${category}/${slug}/`;
}

export function getAllTools(): (ToolMeta & { category: ToolCategory })[] {
  return (Object.keys(TOOLS) as ToolCategory[]).flatMap((category) =>
    TOOLS[category].map((tool) => ({ ...tool, category })),
  );
}
