// Generated by scripts/import-fps-data.mjs. Review version changes before refreshing.
export const FPS_DATA = {
  "cs2": {
    "version": "2000919",
    "revision": "ce2a2deb0cba2f7e8443901690c0abdb5191b7ab",
    "sha256": {
      "weapons": "3289d4dba65b1ef3f884c389448c8a6c6db8691442c18a7aaddb28434aaf250d",
      "convars": "58428ff69e1580052d5ef5da403c50bc600eb415d520f3a58c15008dc2217273"
    },
    "variables": {
      "m_yaw": 0.022,
      "m_pitch": 0.022,
      "sv_accelerate": 5.5,
      "sv_friction": 5.2,
      "sv_stopspeed": 80
    },
    "weapons": {
      "ak47": {
        "m_nDamage": 36,
        "m_iMaxClip1": 30,
        "m_flCycleTime": 0.1,
        "m_flMaxSpeed": [
          215,
          215
        ],
        "m_flSpread": [
          0.0006,
          0.0006
        ],
        "m_flInaccuracyStand": [
          0.00641,
          0.00641
        ],
        "m_flInaccuracyCrouch": [
          0.00481,
          0.00481
        ],
        "m_flInaccuracyMove": [
          0.17506,
          0.17506
        ],
        "m_flRecoveryTimeStand": 0.368,
        "m_flRecoveryTimeCrouch": 0.305257,
        "m_flHeadshotMultiplier": 4,
        "m_flArmorRatio": 1.55,
        "m_flRangeModifier": 0.98,
        "m_flDisallowAttackAfterReloadStartDuration": 2.466667,
        "m_nRecoilSeed": 223
      },
      "m4a1s": {
        "m_nDamage": 38,
        "m_iMaxClip1": 20,
        "m_flCycleTime": 0.1,
        "m_flMaxSpeed": [
          225,
          225
        ],
        "m_flSpread": [
          0.0006,
          0.0005
        ],
        "m_flInaccuracyStand": [
          0.0049,
          0.0049
        ],
        "m_flInaccuracyCrouch": [
          0.0041,
          0.0041
        ],
        "m_flInaccuracyMove": [
          0.09288,
          0.122
        ],
        "m_flRecoveryTimeStand": 0.338941,
        "m_flRecoveryTimeCrouch": 0.2421,
        "m_flHeadshotMultiplier": 3.475,
        "m_flArmorRatio": 1.4,
        "m_flRangeModifier": 0.94,
        "m_flDisallowAttackAfterReloadStartDuration": 3.066667,
        "m_nRecoilSeed": 38965
      }
    }
  },
  "valorant": {
    "version": "13.06.00.5590001",
    "buildDate": "2026-09-25T18:14:25Z",
    "sha256": "8538453ba67f8a6c4885452cad10129a846b9499a069b5e74823d2848cedef7f",
    "weapons": {
      "vandal": {
        "fireRate": 9.75,
        "magazineSize": 25,
        "runSpeedMultiplier": 0.8,
        "equipTimeSeconds": 1,
        "reloadTimeSeconds": 2.5,
        "firstBulletAccuracy": 0.25,
        "shotgunPelletCount": 1,
        "wallPenetration": "EWallPenetrationDisplayType::Medium",
        "feature": null,
        "fireMode": null,
        "altFireType": "EWeaponAltFireDisplayType::ADS",
        "adsStats": {
          "zoomMultiplier": 1.25,
          "fireRate": 8.775,
          "runSpeedMultiplier": 0.76,
          "burstCount": 1,
          "firstBulletAccuracy": 0.1575
        },
        "altShotgunStats": null,
        "airBurstStats": null,
        "damageRanges": [
          {
            "rangeStartMeters": 0,
            "rangeEndMeters": 50,
            "headDamage": 160,
            "bodyDamage": 40,
            "legDamage": 34
          }
        ]
      },
      "phantom": {
        "fireRate": 11,
        "magazineSize": 30,
        "runSpeedMultiplier": 0.8,
        "equipTimeSeconds": 1,
        "reloadTimeSeconds": 2.5,
        "firstBulletAccuracy": 0.2,
        "shotgunPelletCount": 1,
        "wallPenetration": "EWallPenetrationDisplayType::Medium",
        "feature": "EWeaponStatsFeature::Silenced",
        "fireMode": null,
        "altFireType": "EWeaponAltFireDisplayType::ADS",
        "adsStats": {
          "zoomMultiplier": 1.25,
          "fireRate": 9.9,
          "runSpeedMultiplier": 0.76,
          "burstCount": 1,
          "firstBulletAccuracy": 0.11000001
        },
        "altShotgunStats": null,
        "airBurstStats": null,
        "damageRanges": [
          {
            "rangeStartMeters": 0,
            "rangeEndMeters": 20,
            "headDamage": 156,
            "bodyDamage": 39,
            "legDamage": 33.15
          },
          {
            "rangeStartMeters": 20,
            "rangeEndMeters": 50,
            "headDamage": 140,
            "bodyDamage": 35,
            "legDamage": 29.75
          }
        ]
      }
    }
  }
};
