import { FPS_DATA } from './fps-data.mjs';
import { FPS_SOURCES } from './fps-sources.mjs';
import { FPS_AUDIO_ASSETS } from './fps-audio.mjs';

export const FPS_CONFIG = {
  revision: '2026-10-02.1',
  simulation: {
    step: 1 / 240,
    // Brief render stalls must not eject the player from mouse capture.
    maxFrameGap: 1,
    pitchLimit: 85,
    epsilon: 1e-8,
    shotLimit: 1500,
    timelineLimit: 120,
  },
  recoilModel: {
    horizontalFrequency: 1.3,
    verticalRamp: 0.025,
    minimumKick: 0.2,
    fireSpreadPerRound: 0.00035,
    recoveryDelayRatio: 1.5,
  },
  storage: {
    version: 1,
    preferences: 'ct-fps-prefs',
    history: 'ct-fps-history',
    capacity: 80,
    impactCapacity: 64,
    timelineCapacity: 40,
  },
  keys: {
    forward: 'KeyW',
    back: 'KeyS',
    left: 'KeyA',
    right: 'KeyD',
    walk: 'ShiftLeft',
    crouch: 'ControlLeft',
    reload: 'KeyR',
  },
  defaults: {
    game: 'cs2',
    weapon: 'ak47',
    mode: 'free',
    duration: 60,
    distance: 12,
    count: 12,
    speed: 1.5,
    difficulty: 'standard',
    dpi: 800,
    aspect: 'native',
    cm360: 0,
    calibrationGain: 0,
    turnMultiplier: 4,
    sector: 'front',
    movingBots: false,
    infiniteAmmo: true,
    headOnlyBots: true,
    muted: false,
    volume: 60,
    shotVolume: 80,
    hitVolume: 65,
    showWeapon: true,
    weaponMotion: true,
    quality: 'balanced',
  },
  controls: {
    duration: { min: 15, max: 180, step: 15, unit: 's' },
    distance: { min: 5, max: 40, step: 1, unit: 'm' },
    count: { min: 1, max: 24, step: 1, unit: '' },
    speed: { min: 0.5, max: 4, step: 0.25, unit: 'm/s' },
    dpi: { min: 100, max: 32000, step: 100, unit: 'DPI' },
    sensitivity: { min: 0.01, max: 10, step: 0.01, unit: '' },
    fov: { min: 60, max: 120, step: 1, unit: 'deg' },
    cm360: { min: 0, max: 200, step: 0.1, unit: 'cm' },
    calibrationGain: { min: 0, max: 3, step: 0.000001, unit: 'deg/count' },
    turnMultiplier: { min: 0.25, max: 12, step: 0.25, unit: '×' },
    volume: { min: 0, max: 100, step: 5, unit: '%' },
    shotVolume: { min: 0, max: 100, step: 5, unit: '%' },
    hitVolume: { min: 0, max: 100, step: 5, unit: '%' },
  },
  sectors: { front: 90, half: 180, surround: 360 },
  presets: {
    botWarmup: {
      mode: 'free',
      count: 12,
      distance: 12,
      sector: 'front',
      movingBots: false,
      infiniteAmmo: true,
      headOnlyBots: true,
    },
    ballWarmup: {
      mode: 'dots',
      count: 6,
      distance: 10,
      difficulty: 'standard',
    },
    recoilWarmup: { mode: 'spray', distance: 10, duration: 60 },
  },
  calibration: { distanceCm: 10, minCounts: 20 },
  difficulties: {
    easy: { targetScale: 1.4, speedScale: 0.75 },
    standard: { targetScale: 1, speedScale: 1 },
    hard: { targetScale: 0.75, speedScale: 1.25 },
  },
  quality: {
    balanced: {
      pixelRatio: 1.5,
      antialias: true,
      shadows: true,
      shadowMap: 1024,
      sphereSegments: 32,
    },
    performance: {
      pixelRatio: 1,
      antialias: false,
      shadows: false,
      shadowMap: 0,
      sphereSegments: 20,
    },
  },
  scene: {
    materials: {
      roughness: 0.78,
      metalness: 0.12,
      weaponRoughness: 0.36,
      weaponMetalness: 0.65,
      ballRoughness: 0.28,
    },
    width: 96,
    depth: 96,
    height: 6,
    roomMargin: 6,
    roomMinimumHalf: 20,
    playerLimit: 4,
    spawnX: 0,
    spawnZ: 3,
    eyeHeight: 1.6,
    crouchEyeHeight: 1.1,
    bodyRadius: 0.22,
    target: {
      headY: 1.6,
      headRadius: 0.13,
      torsoMin: 0.75,
      torsoMax: 1.43,
      torsoWidth: 0.5,
      legMin: 0,
      legMax: 0.75,
      legWidth: 0.35,
      depth: 0.35,
      crouchScale: 0.75,
    },
    targetSpacing: 1.3,
    targetSpan: 5,
    respawnSeconds: 0.35,
    botRespawnSeconds: 0.12,
    ball: {
      radius: 0.18,
      minY: 0.9,
      maxY: 3.2,
      respawnSeconds: 0.08,
      spacing: 1.5,
      jitter: 0.5,
    },
    bot: { radialJitter: 0.08, angularJitter: 0.35, movementSpan: 1.2 },
    architecture: {
      wallThickness: 0.2,
      floorThickness: 0.1,
      gridSpacing: 2,
      gridElevation: 0.006,
      platformTop: 0.002,
      platformSize: 8,
      platformEdge: 0.05,
      headLineThickness: 0.025,
      stripeY: 3.8,
      stripeHeight: 0.3,
      lightIntensity: 2.2,
      keyIntensity: 3,
      fillIntensity: 0.8,
      keyPosition: { x: -8, y: 12, z: 8 },
      panelSpacing: 6,
      panelWidth: 0.16,
      panelInset: 0.05,
      baseHeight: 0.35,
      lightHeight: 5.6,
      lightThickness: 0.06,
      labelSize: 1.5,
      labelResolution: 256,
      shadowOpacity: 0.18,
      shadowRadius: 0.38,
    },
    mannequin: {
      beltHeight: 0.06,
      vestInset: 0.015,
      bevel: 0.025,
      segments: 3,
      seam: 0.012,
      visorHeight: 0.04,
    },
    cover: { min: { x: -0.6, y: 0, z: 0.1 }, max: { x: 0.6, y: 2.2, z: 0.7 } },
    gun: {
      offset: { x: 0.22, y: -0.19, z: -0.57 },
      adsOffset: { x: 0, y: -0.055, z: -0.42 },
      fov: 65,
      near: 0.01,
      far: 4,
      body: { x: 0.065, y: 0.075, z: 0.3 },
      barrel: { radius: 0.012, length: 0.3, segments: 12 },
      magazine: { x: 0.045, y: 0.14, z: 0.07 },
      grip: { x: 0.045, y: 0.1, z: 0.05 },
      stock: { x: 0.045, y: 0.065, z: 0.2 },
      hand: { x: 0.06, y: 0.07, z: 0.08 },
      armLength: 0.23,
      scale: 0.8,
      fingerRadius: 0.008,
      gloveSegments: 12,
      bevel: 0.008,
      kickDistance: 0.028,
      kickAngle: 0.035,
      kickDecay: 20,
      swayDistance: 0.005,
      swayFrequency: 9,
      reloadDip: 0.12,
      reloadAngle: 0.45,
      flashSeconds: 0.045,
      flashRadius: 0.026,
      flashLength: 0.13,
      profiles: {
        ak47: {
          accent: '#987147',
          barrel: 0.3,
          silencer: 0,
          magazineAngle: -0.22,
          rail: false,
          stock: 0.2,
        },
        m4a1s: {
          accent: '#526879',
          barrel: 0.26,
          silencer: 0.18,
          magazineAngle: -0.08,
          rail: true,
          stock: 0.18,
        },
        vandal: {
          accent: '#657a88',
          barrel: 0.31,
          silencer: 0,
          magazineAngle: -0.16,
          rail: true,
          stock: 0.22,
        },
        phantom: {
          accent: '#487d81',
          barrel: 0.23,
          silencer: 0.15,
          magazineAngle: -0.04,
          rail: true,
          stock: 0.17,
        },
      },
    },
    palette: {
      background: '#e9eff3',
      floor: '#8395a2',
      wall: '#dce5eb',
      grid: '#a5b4bf',
      target: '#40576a',
      head: '#c9a96e',
      cover: '#526577',
      ink: '#152635',
      hit: '#39d2be',
      miss: '#ff745b',
      ball: '#22bfd3',
      platform: '#718591',
      vest: '#263e51',
      visor: '#9fdfeb',
      light: '#f1faff',
      flash: '#ffe1a0',
      glove: '#304555',
    },
    impacts: { lifetime: 4, radius: 0.025, maximum: 100, reportSpanDegrees: 8 },
  },
  feedback: {
    hudInterval: 0.1,
    flashSeconds: 0.1,
    timelineWindow: 0.8,
    crosshair: { size: 12, gap: 4, stroke: 2, color: '#f1faff', outline: '#152635' },
    hitMarkerSize: 22,
    markerSeconds: 0.14,
    audio: {
      assets: FPS_AUDIO_ASSETS,
      loadTimeoutMs: 5000,
      maxVoices: 24,
      compressor: { threshold: -18, knee: 12, ratio: 4, attack: 0.003, release: 0.06 },
      maxLateness: 0.1,
      fadeSeconds: 0.015,
      floorGain: 0.0001,
      hitHz: 1050,
      headHz: 1500,
      completeHz: 1800,
      hitSeconds: 0.06,
      completeSeconds: 0.1,
      feedbackGain: 0.22,
      reloadGain: 0.6,
      dryGain: 0.3,
      profiles: {
        ak47: { sample: 'ak47', rate: 1, gain: 0.75, lowpass: 16000 },
        m4a1s: { sample: 'ar15', rate: 1.12, gain: 0.5, lowpass: 2500 },
        vandal: { sample: 'ak47', rate: 1.06, gain: 0.68, lowpass: 13000 },
        phantom: { sample: 'ar15', rate: 1.04, gain: 0.45, lowpass: 3000 },
      },
    },
  },
  aspects: ['native', 'bars', 'stretch'],
};

/** Every gameplay field has a unit, source/version and explicit fidelity status. */
function profile(id, name, values, units, verified = {}, source = '') {
  return {
    id,
    name,
    values,
    evidence: Object.fromEntries(
      Object.keys(values).map((key) => [
        key,
        {
          unit: units[key] || 'ratio',
          status: key in verified ? 'source' : 'approximate',
          source:
            key in verified ? source : 'CloverTools training model; no original-game measurement',
          field: verified[key] || '',
          version:
            id === 'cs2' || id === 'ak47' || id === 'm4a1s'
              ? FPS_DATA.cs2.version
              : FPS_DATA.valorant.version,
        },
      ]),
    ),
  };
}
const cv = FPS_DATA.cs2.variables;
export const GAME_PROFILES = {
  cs2: profile(
    'cs2',
    'CS2',
    {
      yaw: cv.m_yaw,
      pitch: cv.m_pitch,
      referenceAspect: 4 / 3,
      defaultFov: 90,
      defaultSensitivity: 1,
      acceleration: cv.sv_accelerate,
      friction: cv.sv_friction,
      stopSpeed: cv.sv_stopspeed * 0.0254,
      stopRatio: 0.34,
      walkRatio: 0.52,
      crouchRatio: 0.34,
      unitScale: 0.0254,
      health: 100,
      legMultiplier: 0.75,
      armorDivisor: 2,
      rangeReferenceUnits: 500,
      eyeHeight: 1.6,
      crouchEyeHeight: 1.1,
      aimRecovery: 0.06,
    },
    {
      yaw: 'deg/count/sensitivity',
      pitch: 'deg/count/sensitivity',
      defaultFov: 'deg at 4:3',
      acceleration: '1/s',
      friction: '1/s',
      stopSpeed: 'm/s',
      health: 'HP',
      unitScale: 'm/Source unit',
      rangeReferenceUnits: 'Source units',
      eyeHeight: 'm',
      crouchEyeHeight: 'm',
      aimRecovery: 's',
    },
    {
      yaw: 'm_yaw',
      pitch: 'm_pitch',
      acceleration: 'sv_accelerate',
      friction: 'sv_friction',
      stopSpeed: 'sv_stopspeed × unitScale',
    },
    FPS_SOURCES.cs2.convars,
  ),
  valorant: profile(
    'valorant',
    'VALORANT',
    {
      yaw: 0.07,
      pitch: 0.07,
      referenceAspect: 16 / 9,
      defaultFov: 103,
      defaultSensitivity: 0.35,
      acceleration: 18,
      friction: 18,
      stopSpeed: 1.5,
      stopRatio: 0.275,
      walkRatio: 0.6,
      crouchRatio: 0.55,
      unitScale: 1,
      health: 150,
      eyeHeight: 1.6,
      crouchEyeHeight: 1.1,
      aimRecovery: 0.05,
    },
    {
      yaw: 'deg/count/sensitivity',
      pitch: 'deg/count/sensitivity',
      defaultFov: 'deg at 16:9',
      acceleration: '1/s',
      friction: '1/s',
      stopSpeed: 'm/s',
      health: 'HP + shield',
      unitScale: 'm/m',
      eyeHeight: 'm',
      crouchEyeHeight: 'm',
      aimRecovery: 's',
    },
  ),
};

const weaponUnits = {
  interval: 's',
  magazine: 'rounds',
  reload: 's',
  damage: 'HP',
  headMultiplier: 'ratio',
  maxSpeed: 'm/s',
  spread: 'rad',
  standSpread: 'rad',
  crouchSpread: 'rad',
  moveSpread: 'rad',
  recovery: 's',
  recoilVertical: 'deg/shot',
  recoilHorizontal: 'deg/shot',
  recoilStart: 'round',
  recoilCap: 'deg',
  adsZoom: 'ratio',
  adsInterval: 's',
  adsSpread: 'rad',
};
function csWeapon(id, name, recoil) {
  const d = FPS_DATA.cs2.weapons[id];
  const values = {
    game: 'cs2',
    interval: d.m_flCycleTime,
    magazine: d.m_iMaxClip1,
    // Attack-lock time is not advertised as a measured full reload animation.
    reload: d.m_flDisallowAttackAfterReloadStartDuration,
    damage: d.m_nDamage,
    headMultiplier: d.m_flHeadshotMultiplier,
    armorRatio: d.m_flArmorRatio,
    rangeModifier: d.m_flRangeModifier,
    maxSpeed: d.m_flMaxSpeed[0] * GAME_PROFILES.cs2.values.unitScale,
    spread: d.m_flSpread[0],
    standSpread: d.m_flInaccuracyStand[0],
    crouchSpread: d.m_flInaccuracyCrouch[0],
    moveSpread: d.m_flInaccuracyMove[0],
    recovery: d.m_flRecoveryTimeStand,
    recoilVertical: recoil[0],
    recoilHorizontal: recoil[1],
    recoilStart: recoil[2],
    recoilCap: recoil[3],
    adsZoom: 1,
    adsInterval: d.m_flCycleTime,
    adsSpread: d.m_flInaccuracyStand[0],
  };
  return profile(
    id,
    name,
    values,
    { ...weaponUnits, game: 'id', rangeModifier: 'ratio per 500 Source units' },
    {
      interval: 'm_flCycleTime',
      magazine: 'm_iMaxClip1',
      damage: 'm_nDamage',
      headMultiplier: 'm_flHeadshotMultiplier',
      armorRatio: 'm_flArmorRatio',
      rangeModifier: 'm_flRangeModifier',
      maxSpeed: 'm_flMaxSpeed[0] × unitScale',
      spread: 'm_flSpread[0]',
      standSpread: 'm_flInaccuracyStand[0]',
      crouchSpread: 'm_flInaccuracyCrouch[0]',
      moveSpread: 'm_flInaccuracyMove[0]',
      recovery: 'm_flRecoveryTimeStand',
    },
    FPS_SOURCES.cs2.weapons,
  );
}
function valWeapon(id, name, recoil) {
  const d = FPS_DATA.valorant.weapons[id];
  return profile(
    id,
    name,
    {
      game: 'valorant',
      interval: 1 / d.fireRate,
      magazine: d.magazineSize,
      reload: d.reloadTimeSeconds,
      damage: d.damageRanges[0].bodyDamage,
      headMultiplier: d.damageRanges[0].headDamage / d.damageRanges[0].bodyDamage,
      armorRatio: 2,
      rangeModifier: 1,
      damageRanges: d.damageRanges,
      maxSpeed: 6.75 * d.runSpeedMultiplier,
      spread: 0,
      standSpread: (d.firstBulletAccuracy * Math.PI) / 180,
      // 9.10 raised rifle running inaccuracy to 6; the angular distribution remains approximate.
      crouchSpread: ((d.firstBulletAccuracy * Math.PI) / 180) * 0.8,
      moveSpread: (6 * Math.PI) / 180,
      recovery: recoil[4],
      recoilVertical: recoil[0],
      recoilHorizontal: recoil[1],
      recoilStart: recoil[2],
      recoilCap: recoil[3],
      adsZoom: d.adsStats.zoomMultiplier,
      adsInterval: 1 / d.adsStats.fireRate,
      adsSpread: (d.adsStats.firstBulletAccuracy * Math.PI) / 180,
    },
    {
      ...weaponUnits,
      game: 'id',
      damageRanges: 'm, HP',
      rangeModifier: 'ratio',
    },
    {
      interval: '1/fireRate',
      magazine: 'magazineSize',
      reload: 'reloadTimeSeconds',
      damage: 'damageRanges[0].bodyDamage',
      headMultiplier: 'headDamage/bodyDamage',
      damageRanges: 'damageRanges',
      standSpread: 'firstBulletAccuracy × PI/180',
      adsZoom: 'adsStats.zoomMultiplier',
      adsInterval: '1/adsStats.fireRate',
      adsSpread: 'adsStats.firstBulletAccuracy × PI/180',
    },
    FPS_SOURCES.valorant.weapons,
  );
}
export const WEAPON_PROFILES = {
  ak47: csWeapon('ak47', 'AK-47', [0.65, 0.3, 6, 8]),
  m4a1s: csWeapon('m4a1s', 'M4A1-S', [0.48, 0.22, 5, 6]),
  vandal: valWeapon('vandal', 'Vandal', [0.7, 0.48, 6, 9, 0.45]),
  phantom: valWeapon('phantom', 'Phantom', [0.5, 0.4, 7, 7, 0.35]),
};

// Scenario behaviors belong to the mode registry; editable spawn policies live here.
export const TRAINING_MODES = {
  micro: {
    behavior: 'random',
    count: 1,
    moving: false,
    cover: false,
    headOnly: true,
    timed: true,
    metrics: ['firstRate', 'meanHitMs'],
  },
  strafe: {
    behavior: 'random',
    count: 1,
    moving: false,
    cover: false,
    headOnly: true,
    timed: true,
    metrics: ['movingRate', 'stableDelayMs'],
  },
  peek: {
    behavior: 'lanes',
    count: 2,
    moving: false,
    cover: true,
    headOnly: false,
    timed: true,
    metrics: ['placementDegrees', 'firstRate', 'meanHitMs'],
  },
  spray: {
    behavior: 'center',
    count: 1,
    moving: false,
    cover: false,
    headOnly: false,
    timed: true,
    persistent: true,
    metrics: ['meanHitMs', 'recoilDegrees'],
  },
  track: {
    behavior: 'center',
    count: 1,
    moving: true,
    cover: false,
    headOnly: false,
    timed: true,
    persistent: true,
    metrics: ['coverage'],
  },
  switch: {
    behavior: 'lanes',
    count: null,
    moving: false,
    cover: false,
    headOnly: false,
    timed: true,
    metrics: ['switchMs', 'firstRate'],
  },
  free: {
    behavior: 'ring',
    count: null,
    moving: false,
    cover: false,
    headOnly: false,
    timed: false,
    customBots: true,
    metrics: ['movingRate', 'coverage', 'switchMs'],
  },
  dots: {
    behavior: 'balls',
    count: null,
    moving: false,
    cover: false,
    headOnly: false,
    timed: true,
    ball: true,
    precision: true,
    metrics: ['firstRate', 'meanHitMs', 'switchMs'],
  },
};
