import { FPS_DATA } from './fps-data.mjs';
import { FPS_SOURCES } from './fps-sources.mjs';

export const FPS_CONFIG = {
  revision: '2026-10-01.1',
  simulation: {
    step: 1 / 240,
    // Brief render stalls must not eject the player from mouse capture.
    maxFrameGap: 1,
    pitchLimit: 85,
    epsilon: 1e-8,
    shotLimit: 1500,
    timelineLimit: 120,
  },
  recoilModel: {
    horizontalFrequency: 1.3,
    verticalRamp: 0.025,
    minimumKick: 0.2,
    fireSpreadPerRound: 0.00035,
    recoveryDelayRatio: 1.5,
  },
  storage: {
    version: 1,
    preferences: 'ct-fps-prefs',
    history: 'ct-fps-history',
    capacity: 80,
    impactCapacity: 64,
    timelineCapacity: 40,
  },
  keys: {
    forward: 'KeyW',
    back: 'KeyS',
    left: 'KeyA',
    right: 'KeyD',
    walk: 'ShiftLeft',
    crouch: 'ControlLeft',
    reload: 'KeyR',
  },
  defaults: {
    game: 'cs2',
    weapon: 'ak47',
    mode: 'micro',
    duration: 60,
    distance: 15,
    count: 3,
    speed: 1.5,
    difficulty: 'standard',
    dpi: 800,
    aspect: 'native',
    cm360: 0,
    calibrationGain: 0,
    muted: false,
    quality: 'balanced',
  },
  controls: {
    duration: { min: 15, max: 180, step: 15, unit: 's' },
    distance: { min: 5, max: 40, step: 1, unit: 'm' },
    count: { min: 1, max: 8, step: 1, unit: '' },
    speed: { min: 0.5, max: 4, step: 0.25, unit: 'm/s' },
    dpi: { min: 100, max: 32000, step: 100, unit: 'DPI' },
    sensitivity: { min: 0.01, max: 10, step: 0.01, unit: '' },
    fov: { min: 60, max: 120, step: 1, unit: 'deg' },
    cm360: { min: 0, max: 200, step: 0.1, unit: 'cm' },
    calibrationGain: { min: 0, max: 3, step: 0.000001, unit: 'deg/count' },
  },
  calibration: { distanceCm: 10, minCounts: 20 },
  difficulties: {
    easy: { targetScale: 1.4, speedScale: 0.75 },
    standard: { targetScale: 1, speedScale: 1 },
    hard: { targetScale: 0.75, speedScale: 1.25 },
  },
  quality: {
    balanced: { pixelRatio: 1.5, antialias: true },
    performance: { pixelRatio: 1, antialias: false },
  },
  scene: {
    width: 24,
    depth: 48,
    height: 6,
    playerLimit: 4,
    spawnX: 0,
    spawnZ: 3,
    eyeHeight: 1.6,
    crouchEyeHeight: 1.1,
    bodyRadius: 0.22,
    target: {
      headY: 1.6,
      headRadius: 0.13,
      torsoMin: 0.75,
      torsoMax: 1.43,
      torsoWidth: 0.5,
      legMin: 0,
      legMax: 0.75,
      legWidth: 0.35,
      depth: 0.35,
      crouchScale: 0.75,
    },
    targetSpacing: 1.3,
    targetSpan: 5,
    respawnSeconds: 0.35,
    cover: { min: { x: -0.6, y: 0, z: 0.1 }, max: { x: 0.6, y: 2.2, z: 0.7 } },
    gun: {
      offset: { x: 0.28, y: -0.23, z: -0.5 },
      body: { x: 0.07, y: 0.1, z: 0.3 },
      barrel: { x: 0.035, y: 0.035, z: 0.4 },
    },
    palette: {
      background: '#e8e7e0',
      floor: '#deddd4',
      wall: '#f1f0e9',
      grid: '#b6b6a8',
      target: '#59798a',
      head: '#c9a96e',
      cover: '#8e998e',
      ink: '#3a301f',
      hit: '#22a06b',
      miss: '#d64545',
    },
    impacts: { lifetime: 4, radius: 0.025, maximum: 100, reportSpanDegrees: 8 },
  },
  feedback: {
    hudInterval: 0.1,
    flashSeconds: 0.1,
    timelineWindow: 0.8,
    audio: { hitHz: 760, missHz: 190, duration: 0.045, volume: 0.04 },
  },
  aspects: ['native', 'bars', 'stretch'],
};

/** Every gameplay field has a unit, source/version and explicit fidelity status. */
function profile(id, name, values, units, verified = {}, source = '') {
  return {
    id,
    name,
    values,
    evidence: Object.fromEntries(
      Object.keys(values).map((key) => [
        key,
        {
          unit: units[key] || 'ratio',
          status: key in verified ? 'source' : 'approximate',
          source:
            key in verified ? source : 'CloverTools training model; no original-game measurement',
          field: verified[key] || '',
          version:
            id === 'cs2' || id === 'ak47' || id === 'm4a1s'
              ? FPS_DATA.cs2.version
              : FPS_DATA.valorant.version,
        },
      ]),
    ),
  };
}
const cv = FPS_DATA.cs2.variables;
export const GAME_PROFILES = {
  cs2: profile(
    'cs2',
    'CS2',
    {
      yaw: cv.m_yaw,
      pitch: cv.m_pitch,
      referenceAspect: 4 / 3,
      defaultFov: 90,
      defaultSensitivity: 1,
      acceleration: cv.sv_accelerate,
      friction: cv.sv_friction,
      stopSpeed: cv.sv_stopspeed * 0.0254,
      stopRatio: 0.34,
      walkRatio: 0.52,
      crouchRatio: 0.34,
      unitScale: 0.0254,
      health: 100,
      legMultiplier: 0.75,
      armorDivisor: 2,
      rangeReferenceUnits: 500,
      eyeHeight: 1.6,
      crouchEyeHeight: 1.1,
      aimRecovery: 0.06,
    },
    {
      yaw: 'deg/count/sensitivity',
      pitch: 'deg/count/sensitivity',
      defaultFov: 'deg at 4:3',
      acceleration: '1/s',
      friction: '1/s',
      stopSpeed: 'm/s',
      health: 'HP',
      unitScale: 'm/Source unit',
      rangeReferenceUnits: 'Source units',
      eyeHeight: 'm',
      crouchEyeHeight: 'm',
      aimRecovery: 's',
    },
    {
      yaw: 'm_yaw',
      pitch: 'm_pitch',
      acceleration: 'sv_accelerate',
      friction: 'sv_friction',
      stopSpeed: 'sv_stopspeed × unitScale',
    },
    FPS_SOURCES.cs2.convars,
  ),
  valorant: profile(
    'valorant',
    'VALORANT',
    {
      yaw: 0.07,
      pitch: 0.07,
      referenceAspect: 16 / 9,
      defaultFov: 103,
      defaultSensitivity: 0.35,
      acceleration: 18,
      friction: 18,
      stopSpeed: 1.5,
      stopRatio: 0.275,
      walkRatio: 0.6,
      crouchRatio: 0.55,
      unitScale: 1,
      health: 150,
      eyeHeight: 1.6,
      crouchEyeHeight: 1.1,
      aimRecovery: 0.05,
    },
    {
      yaw: 'deg/count/sensitivity',
      pitch: 'deg/count/sensitivity',
      defaultFov: 'deg at 16:9',
      acceleration: '1/s',
      friction: '1/s',
      stopSpeed: 'm/s',
      health: 'HP + shield',
      unitScale: 'm/m',
      eyeHeight: 'm',
      crouchEyeHeight: 'm',
      aimRecovery: 's',
    },
  ),
};

const weaponUnits = {
  interval: 's',
  magazine: 'rounds',
  reload: 's',
  damage: 'HP',
  headMultiplier: 'ratio',
  maxSpeed: 'm/s',
  spread: 'rad',
  standSpread: 'rad',
  crouchSpread: 'rad',
  moveSpread: 'rad',
  recovery: 's',
  recoilVertical: 'deg/shot',
  recoilHorizontal: 'deg/shot',
  recoilStart: 'round',
  recoilCap: 'deg',
  adsZoom: 'ratio',
  adsInterval: 's',
  adsSpread: 'rad',
};
function csWeapon(id, name, recoil) {
  const d = FPS_DATA.cs2.weapons[id];
  const values = {
    game: 'cs2',
    interval: d.m_flCycleTime,
    magazine: d.m_iMaxClip1,
    // Attack-lock time is not advertised as a measured full reload animation.
    reload: d.m_flDisallowAttackAfterReloadStartDuration,
    damage: d.m_nDamage,
    headMultiplier: d.m_flHeadshotMultiplier,
    armorRatio: d.m_flArmorRatio,
    rangeModifier: d.m_flRangeModifier,
    maxSpeed: d.m_flMaxSpeed[0] * GAME_PROFILES.cs2.values.unitScale,
    spread: d.m_flSpread[0],
    standSpread: d.m_flInaccuracyStand[0],
    crouchSpread: d.m_flInaccuracyCrouch[0],
    moveSpread: d.m_flInaccuracyMove[0],
    recovery: d.m_flRecoveryTimeStand,
    recoilVertical: recoil[0],
    recoilHorizontal: recoil[1],
    recoilStart: recoil[2],
    recoilCap: recoil[3],
    adsZoom: 1,
    adsInterval: d.m_flCycleTime,
    adsSpread: d.m_flInaccuracyStand[0],
  };
  return profile(
    id,
    name,
    values,
    { ...weaponUnits, game: 'id', rangeModifier: 'ratio per 500 Source units' },
    {
      interval: 'm_flCycleTime',
      magazine: 'm_iMaxClip1',
      damage: 'm_nDamage',
      headMultiplier: 'm_flHeadshotMultiplier',
      armorRatio: 'm_flArmorRatio',
      rangeModifier: 'm_flRangeModifier',
      maxSpeed: 'm_flMaxSpeed[0] × unitScale',
      spread: 'm_flSpread[0]',
      standSpread: 'm_flInaccuracyStand[0]',
      crouchSpread: 'm_flInaccuracyCrouch[0]',
      moveSpread: 'm_flInaccuracyMove[0]',
      recovery: 'm_flRecoveryTimeStand',
    },
    FPS_SOURCES.cs2.weapons,
  );
}
function valWeapon(id, name, recoil) {
  const d = FPS_DATA.valorant.weapons[id];
  return profile(
    id,
    name,
    {
      game: 'valorant',
      interval: 1 / d.fireRate,
      magazine: d.magazineSize,
      reload: d.reloadTimeSeconds,
      damage: d.damageRanges[0].bodyDamage,
      headMultiplier: d.damageRanges[0].headDamage / d.damageRanges[0].bodyDamage,
      armorRatio: 2,
      rangeModifier: 1,
      damageRanges: d.damageRanges,
      maxSpeed: 6.75 * d.runSpeedMultiplier,
      spread: 0,
      standSpread: (d.firstBulletAccuracy * Math.PI) / 180,
      // 9.10 raised rifle running inaccuracy to 6; the angular distribution remains approximate.
      crouchSpread: ((d.firstBulletAccuracy * Math.PI) / 180) * 0.8,
      moveSpread: (6 * Math.PI) / 180,
      recovery: recoil[4],
      recoilVertical: recoil[0],
      recoilHorizontal: recoil[1],
      recoilStart: recoil[2],
      recoilCap: recoil[3],
      adsZoom: d.adsStats.zoomMultiplier,
      adsInterval: 1 / d.adsStats.fireRate,
      adsSpread: (d.adsStats.firstBulletAccuracy * Math.PI) / 180,
    },
    { ...weaponUnits, game: 'id', damageRanges: 'm, HP', rangeModifier: 'ratio' },
    {
      interval: '1/fireRate',
      magazine: 'magazineSize',
      reload: 'reloadTimeSeconds',
      damage: 'damageRanges[0].bodyDamage',
      headMultiplier: 'headDamage/bodyDamage',
      damageRanges: 'damageRanges',
      standSpread: 'firstBulletAccuracy × PI/180',
      adsZoom: 'adsStats.zoomMultiplier',
      adsInterval: '1/adsStats.fireRate',
      adsSpread: 'adsStats.firstBulletAccuracy × PI/180',
    },
    FPS_SOURCES.valorant.weapons,
  );
}
export const WEAPON_PROFILES = {
  ak47: csWeapon('ak47', 'AK-47', [0.65, 0.3, 6, 8]),
  m4a1s: csWeapon('m4a1s', 'M4A1-S', [0.48, 0.22, 5, 6]),
  vandal: valWeapon('vandal', 'Vandal', [0.7, 0.48, 6, 9, 0.45]),
  phantom: valWeapon('phantom', 'Phantom', [0.5, 0.4, 7, 7, 0.35]),
};

// Scenario behaviors belong to the mode registry; editable spawn policies live here.
export const TRAINING_MODES = {
  micro: {
    behavior: 'random',
    count: 1,
    moving: false,
    cover: false,
    headOnly: true,
    timed: true,
    metrics: ['firstRate', 'meanHitMs'],
  },
  strafe: {
    behavior: 'random',
    count: 1,
    moving: false,
    cover: false,
    headOnly: true,
    timed: true,
    metrics: ['movingRate', 'stableDelayMs'],
  },
  peek: {
    behavior: 'lanes',
    count: 2,
    moving: false,
    cover: true,
    headOnly: false,
    timed: true,
    metrics: ['placementDegrees', 'firstRate', 'meanHitMs'],
  },
  spray: {
    behavior: 'center',
    count: 1,
    moving: false,
    cover: false,
    headOnly: false,
    timed: true,
    persistent: true,
    metrics: ['meanHitMs', 'recoilDegrees'],
  },
  track: {
    behavior: 'center',
    count: 1,
    moving: true,
    cover: false,
    headOnly: false,
    timed: true,
    persistent: true,
    metrics: ['coverage'],
  },
  switch: {
    behavior: 'lanes',
    count: null,
    moving: false,
    cover: false,
    headOnly: false,
    timed: true,
    metrics: ['switchMs', 'firstRate'],
  },
  free: {
    behavior: 'lanes',
    count: null,
    moving: true,
    cover: false,
    headOnly: false,
    timed: false,
    metrics: ['movingRate', 'coverage'],
  },
};
