#!/usr/bin/env python3
"""
Generate standalone HTML files for all tools listed in tools.json.
Uses base64 to avoid JS string escaping issues.
"""

import base64
import json
import os
import re
from pathlib import Path

BASE = Path('/home/yock/clover-tools-v2')
OUT_DIR = BASE / 'dist' / 'tools'
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(BASE / 'tools.json') as f:
    tools_data = json.load(f)

with open(BASE / 'generator.js') as f:
    gen_content = f.read()

# Find already-implemented tool keys
buildscripts = re.search(r'function buildToolScript\(tool\) \{([\s\S]*?)^\}', gen_content, re.MULTILINE)
existing_script_keys = set(re.findall(r"'([^']+)':", buildscripts.group(1))) if buildscripts else set()

buildcontents = re.search(r'function buildToolContentHtml\(tool\) \{([\s\S]*?)^\}', gen_content, re.MULTILINE)
existing_content_keys = set(re.findall(r"'([^']+)':", buildcontents.group(1))) if buildcontents else set()

print(f"Existing scripts: {len(existing_script_keys)}, Existing contents: {len(existing_content_keys)}")

# Load component templates
SVG_SPRITE = open(BASE / 'templates/components/svg-sprite.html').read().strip()
HEADER_HTML = open(BASE / 'templates/components/header.html').read().strip()
FOOTER_FULL = open(BASE / 'templates/components/footer.html').read().strip()
FOOTER_TOOL = FOOTER_FULL.replace(
    '<!-- FOOTER_SHARE_BTN will be replaced by generator.js for tool pages -->',
    '<button class="share-btn" id="shareBtn" style="background:var(--primary);color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;cursor:pointer;font-size:0.9rem;">📋 分享工具</button>'
)
SHARE_SCRIPT = 'document.getElementById("shareBtn").onclick=function(){navigator.clipboard.writeText(window.location.href).then(function(){CT.showToast("\\u94fe\\u63a5\\u5df2\\u590d\\u5236\\uff01");}).catch(function(){CT.showToast("\\u590d\\u5236\\u5931\\u8d25");});};'

# ============================================================
# All tool definitions: key -> (html_content, js_code)
# JS code is stored as unicode-escaped string
# ============================================================

TOOLS = {

    # ---- JSON 工具 ----
    'json/validator': (
        '''<div class="tool-card"><h3>输入 JSON</h3><textarea id="input" placeholder="粘贴 JSON 数据..."></textarea></div><div class="output-box"><h3>结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output');function v(){const t=i.value.trim();if(!t){o.value='';return;}try{const p=JSON.parse(t);o.value='OK\n'+JSON.stringify(p,null,2);}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',v);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);v();'''
    ),
    'json/to-csv': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON 数组" style="min-height:120px;font-family:monospace;"></textarea><div class="btn-row" style="margin-top:0.5rem;"><button class="btn btn-primary" id="toCsv">JSON→CSV</button><button class="btn btn-secondary" id="fromCsv">CSV→JSON</button></div></div><div class="output-box"><h3>输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output');function tc(){try{const t=i.value.trim();if(!t){o.value='';return;}const d=JSON.parse(t),a=Array.isArray(d)?d:[d];if(!a.length){o.value='';return;}const h=[...new Set(a.flatMap(x=>Object.keys(x))),cs=a.map(r=>h.map(h=>{const v=r[h]===undefined||r[h]===null?'':String(r[h]);return v.includes(',')||v.includes('"')||v.includes('\n')?'"'+v.replace(/"/g,'""')+'"':v;}).join(',')).join('\n');o.value=[h.join(','),cs].join('\n');}catch(e){o.value='Error: '+e.message;}}function fc(){try{const t=i.value.trim();if(!t){o.value='';return;}const ls=t.split('\n'),h=ls[0].split(',').map(x=>x.trim().replace(/^"|"$/g,'')),arr=ls.slice(1).filter(x=>x.trim()).map(line=>{const vals=[],q=false,cur='',i=0;while(i<line.length){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i+=2;}else{q=!q;i++;}}else if(c===','&&!q){vals.push(cur.trim());cur='';i++;}else{cur+=c;i++;}}vals.push(cur.trim());const obj={};h.forEach((h,idx)=>{obj[h]=vals[idx]||'';});return obj;});o.value=JSON.stringify(arr.length===1?arr[0]:arr,null,2);}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',tc);document.getElementById('toCsv').onclick=tc;document.getElementById('fromCsv').onclick=fc;document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/to-toml': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea></div><div class="output-box"><h3>TOML 输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output');function tt(obj,indent=0){const p='  '.repeat(indent);if(typeof obj!=='object'||obj===null)return p+(typeof obj==='string'?'"'+obj+'"':obj);if(Array.isArray(obj))return obj.map(v=>{const s=tt(v,indent+1);return p+'- '+(typeof v==='object'&&v!==null?'\n'+s:s.trim());}).join('\n');return Object.entries(obj).map(([k,v])=>{if(typeof v!=='object'||v===null)return p+k+' = '+(typeof v==='string'?'"'+v+'"':v);return p+'['+k+']\n'+tt(v,indent+1);}).join('\n');}function run(){try{const t=i.value.trim();if(!t){o.value='';return;}const obj=JSON.parse(t);o.value=tt(obj);}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/to-ts': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>类型名称: <input type="text" id="typeName" value="Root" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);"></label></div></div><div class="output-box"><h3>TypeScript 输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output'),tn=document.getElementById('typeName');function ts(obj,name,indent=0){const p='  '.repeat(indent),tm={string:'string',number:'number',boolean:'boolean'};if(typeof obj!=='object'||obj===null)return p+(tm[typeof obj]||'unknown');if(Array.isArray(obj)){if(!obj.length)return p+'unknown[]';const t=[...new Set(obj.map(x=>ts(x,'',indent+1).trim()))];return p+(t.length===1?t[0]+'[]':'('+t.join(' | ')+')[]');}const e=Object.entries(obj);if(!e.length)return p+'Record<string,unknown>';let r='interface '+name+' {\n';for(const[k,v]of e){const opt=k.startsWith('_')?'?':'';const sk=/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k)?k:"'"+k+"'";r+=p+'  '+sk+opt+': '+ts(v,'',indent+1).trim()+';\n';}r+=p+'}';return r;}function run(){try{const t=i.value.trim();if(!t){o.value='';return;}const obj=JSON.parse(t);o.value='export '+ts(obj,tn.value||'Root');}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);tn.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/to-go': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>类型名称: <input type="text" id="typeName" value="Root" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);"></label></div></div><div class="output-box"><h3>Go Struct 输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output'),tn=document.getElementById('typeName');function tg(obj,name,indent=0){const p='  '.repeat(indent),tm={string:'string',number:'float64',boolean:'bool'};if(typeof obj!=='object'||obj===null)return p+(tm[typeof obj]||'interface{}');if(Array.isArray(obj)){if(!obj.length)return p+'[]interface{}';const t=[...new Set(obj.map(x=>tg(x,'',indent+1).trim()))];return p+(t.length===1?'[]'+t[0].replace(/^\*/,''):'[]interface{}');}let r='type '+name+' struct {\n';for(const[k,v]of Object.entries(obj)){const sk=/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k)?k:"'"+k+"'";const tag=/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k)?'':' `json:"'+k+'"`';r+=p+'  '+sk+' '+tg(v,'',indent+1).trim()+tag+'\n';}r+=p+'}';return r;}function run(){try{const t=i.value.trim();if(!t){o.value='';return;}const obj=JSON.parse(t);o.value='package main\n\n'+tg(obj,tn.value||'Root');}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);tn.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/to-rust': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>类型名称: <input type="text" id="typeName" value="Root" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);"></label></div></div><div class="output-box"><h3>Rust Struct 输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),o=document.getElementById('output'),tn=document.getElementById('typeName');function tr(obj,name,indent=0){const p='  '.repeat(indent),tm={string:'String',number:'f64',boolean:'bool'};if(typeof obj!=='object'||obj===null)return p+(tm[typeof obj]||'serde_json::Value');if(Array.isArray(obj)){if(!obj.length)return p+'Vec<serde_json::Value>';const t=[...new Set(obj.map(x=>tr(x,'',indent+1).trim()))];return p+(t.length===1?'Vec<'+t[0].replace(/^\*/,'')+'>':'Vec<serde_json::Value>');}let r='#[derive(Debug,Serialize,Deserialize)]\n'+p+'pub struct '+name+' {\n';for(const[k,v]of Object.entries(obj)){const sk=/^[a-z_][a-z0-9_]*$/.test(k)?k:k;r+=p+'  pub '+sk+': '+tr(v,'',indent+1).trim()+',\n';}r+=p+'}';return r;}function run(){try{const t=i.value.trim();if(!t){o.value='';return;}const obj=JSON.parse(t);o.value='use serde::{Serialize,Deserialize};\n\n'+tr(obj,tn.value||'Root');}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);tn.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/json-path': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>JSONPath: <input type="text" id="pathInput" value="$." placeholder="$.store.book[0]" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);width:60%;"></label></div></div><div class="output-box"><h3>查询结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),p=document.getElementById('pathInput'),o=document.getElementById('output');function jp(obj,path){if(!path.startsWith('$'))path='$'+path;const ts=path.split(/\.(?![^\[\]]*\])|(?<![^\[\]]*\])\[/).filter(Boolean);let cur=[obj];for(const t of ts){if(t==='$')continue;const next=[];if(t==='*'){cur.forEach(c=>{if(Array.isArray(c))next.push(...c);else if(typeof c==='object'&&c!==null)next.push(...Object.values(c));});}else if(/^\d+$/.test(t)){const idx=parseInt(t);cur.forEach(c=>{if(Array.isArray(c)&&c[idx]!==undefined)next.push(c[idx]);});}else if(t.startsWith('[')&&t.endsWith(']')){const idxs=t.slice(1,-1).split(',').map(s=>s.trim());idxs.forEach(idx=>{if(/^\d+$/.test(idx))cur.forEach(c=>{if(Array.isArray(c)&&c[parseInt(idx)]!==undefined)next.push(c[parseInt(idx)]);});});}else{cur.forEach(c=>{if(c&&typeof c==='object'&&t in c)next.push(c[t]);});}cur=next;}return cur;}function run(){try{const t=i.value.trim(),pval=p.value.trim()||'$.';if(!t){o.value='';return;}const obj=JSON.parse(t);o.value=JSON.stringify(jp(obj,pval),null,2);}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);p.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/merge': (
        '''<div class="tool-card"><h3>JSON 1</h3><textarea id="input1" placeholder="第一个 JSON 对象..." style="min-height:100px;font-family:monospace;"></textarea></div><div class="tool-card"><h3>JSON 2</h3><textarea id="input2" placeholder="第二个 JSON 对象..." style="min-height:100px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label><input type="checkbox" id="deepMerge"> 深度合并</label></div></div><div class="output-box"><h3>合并结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:100px;"></textarea></div>''',
        r'''const i1=document.getElementById('input1'),i2=document.getElementById('input2'),o=document.getElementById('output'),dc=document.getElementById('deepMerge');function mg(a,b,d){if(d){if(typeof a==='object'&&typeof b==='object'&&a!==null&&b!==null){if(Array.isArray(a)!==Array.isArray(b))return Array.isArray(b)?b:a;if(Array.isArray(a))return[...a,...b];const r={...a};for(const k of Object.keys(b))r[k]=mg(a[k],b[k],true);return r;}return b!==undefined?b:a;}return{...a,...b};}function run(){try{const v1=i1.value.trim(),v2=i2.value.trim();if(!v1&&!v2){o.value='';return;}const o1=v1?JSON.parse(v1):(Array.isArray(JSON.parse(v2||'{}'))?[]:{});const o2=v2?JSON.parse(v2):{};o.value=JSON.stringify(mg(o1,o2,dc.checked),null,2);}catch(e){o.value='Error: '+e.message;}}i1.addEventListener('input',run);i2.addEventListener('input',run);dc.addEventListener('change',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/generator': (
        '''<div class="tool-card"><h3>JSON 模板</h3><textarea id="template" placeholder="{"name":"{{name}}","age":{{integer(18,80)}},"email":"{{email}}"}" style="min-height:100px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>生成数量: <input type="number" id="count" value="1" min="1" max="100" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);width:80px;"></label><span style="font-size:0.8rem;opacity:0.6;margin-left:0.5rem;">{{name}} {{integer(1,100)}} {{float(0,100)}} {{boolean}} {{email}} {{date}} {{uuid}}</span></div></div><div class="output-box"><h3>生成结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:100px;"></textarea></div>''',
        r'''const ti=document.getElementById('template'),co=document.getElementById('count'),o=document.getElementById('output');function ri(mi,ma){return Math.floor(Math.random()*(ma-mi+1))+mi;}function rf(mi,ma,d){return(Math.random()*(ma-mi)+mi).toFixed(d||2);}function rs(l){return Array.from({length:l||ri(5,12)},()=>String.fromCharCode(ri(97,122))).join('');}function rb(){return Math.random()>0.5;}const fn=['张','李','王','刘','陈','杨','赵','黄','周','吴'],ln=['伟','芳','娜','秀英','敏','静','丽','强','磊','军'],ct=['北京','上海','广州','深圳','杭州','成都','武汉','西安'];function gen(t){if(t===null||t===undefined)return null;if(typeof t==='string'){if(t==='{{firstName}}')return fn[ri(0,fn.length-1)];if(t==='{{lastName}}')return ln[ri(0,ln.length-1)];if(t==='{{name}}')return fn[ri(0,fn.length-1)]+ln[ri(0,ln.length-1)];if(t==='{{city}}')return ct[ri(0,ct.length-1)];if(t==='{{integer}}')return ri(1,1000);if(t==='{{float}}')return parseFloat(rf(0,1000));if(t==='{{boolean}}')return rb();if(t==='{{guid}}'||t==='{{uuid}}')return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&0x3|0x8)).toString(16);});if(t==='{{date}}')return new Date(Date.now()-ri(0,365*3)*86400000).toISOString().split('T')[0];if(t==='{{email}}')return rs(8)+'@example.com';if(t==='{{phone}}')return'1'+ri(3,9)+Array.from({length:9},()=>ri(0,9)).join('');if(t.startsWith('{{integer(')){const m=t.match(/\d+/g).map(Number);return ri(m[0],m[1]);}if(t.startsWith('{{float(')){const m=t.match(/[\d.]+/g).map(Number);return parseFloat(rf(m[0],m[1],m[2]||2));}if(t.startsWith('{{random(')){const o=t.match(/\[(.*?)\]/)[1].split(',');return o[ri(0,o.length-1)].trim();}return t;}if(Array.isArray(t))return t.map(x=>gen(x));if(typeof t==='object'){const r={};for(const k of Object.keys(t))r[k]=gen(t[k]);return r;}return t;}function run(){try{const tpl=ti.value.trim();if(!tpl){o.value='';return;}const cnt=parseInt(co.value)||1,tplobj=JSON.parse(tpl),res=[];for(let i=0;i<Math.min(cnt,100);i++)res.push(gen(tplobj));o.value=JSON.stringify(cnt===1?res[0]:res,null,2);}catch(e){o.value='Error: '+e.message;}}ti.addEventListener('input',run);co.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/sort': (
        '''<div class="tool-card"><h3>JSON 数组</h3><textarea id="input" placeholder="[{"name":"张三","age":28}]" style="min-height:100px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>排序字段: <input type="text" id="sortKey" placeholder="留空按整体排序" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);"></label></div><div class="btn-row"><button class="btn btn-primary" id="sortAsc">升序 ↑</button><button class="btn btn-secondary" id="sortDesc">降序 ↓</button></div></div><div class="output-box"><h3>排序结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:100px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),k=document.getElementById('sortKey'),o=document.getElementById('output');function run(asc){try{const t=i.value.trim();if(!t){o.value='';return;}const d=JSON.parse(t);if(!Array.isArray(d)){o.value=JSON.stringify(d,null,2);return;}const sk=k.value.trim();const s=[...d].sort((a,b)=>{const va=sk?(a[sk]??''):a,vb=sk?(b[sk]??''):b;if(va<vb)return asc?-1:1;if(va>vb)return asc?1:-1;return 0;});o.value=JSON.stringify(s,null,2);}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',()=>run(true));k.addEventListener('input',()=>run(true));document.getElementById('sortAsc').onclick=()=>run(true);document.getElementById('sortDesc').onclick=()=>run(false);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/search': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="input" placeholder="输入 JSON..." style="min-height:120px;font-family:monospace;"></textarea><div style="margin-top:0.5rem;"><label>搜索关键字: <input type="text" id="searchInput" placeholder="输入搜索内容..." style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);width:60%;"></label><label style="margin-left:1rem;"><input type="checkbox" id="caseSensitive"> 区分大小写</label></div></div><div class="output-box"><h3>搜索结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:120px;"></textarea></div>''',
        r'''const i=document.getElementById('input'),s=document.getElementById('searchInput'),o=document.getElementById('output'),cs=document.getElementById('caseSensitive');function searchIn(obj,query,c){const results=[];function tr(o,path){if(typeof o==='object'&&o!==null){const e=Object.entries(o);e.forEach(([k,v])=>tr(v,path?path+'.'+k:k));}else{const str=String(o),q=c?str:str.toLowerCase(),m=c?query:query.toLowerCase();if(q.includes(m))results.push({path,value:o,type:typeof o});}}tr(obj,'');return results;}function run(){try{const t=i.value.trim(),q=s.value;if(!t||!q){o.value='';return;}const obj=JSON.parse(t),results=searchIn(obj,q,cs.checked);if(!results.length){o.value='未找到匹配结果';return;}o.value='找到 '+results.length+' 个匹配：\n\n'+results.map(r=>'路径: '+r.path+'\n值: '+JSON.stringify(r.value)+'\n类型: '+r.type).join('\n\n---\n\n');}catch(e){o.value='Error: '+e.message;}}i.addEventListener('input',run);s.addEventListener('input',run);cs.addEventListener('change',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),
    'json/schema': (
        '''<div class="tool-card"><h3>JSON 数据</h3><textarea id="jsonInput" placeholder="输入 JSON..." style="min-height:100px;font-family:monospace;"></textarea><h3 style="margin-top:1rem;">JSON Schema</h3><textarea id="schemaInput" placeholder="输入 JSON Schema..." style="min-height:100px;font-family:monospace;"></textarea></div><div class="output-box"><h3>验证结果 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="font-family:monospace;min-height:100px;"></textarea></div>''',
        r'''const ji=document.getElementById('jsonInput'),si=document.getElementById('schemaInput'),o=document.getElementById('output');function v(data,schema,path=''){const errors=[],tm={string:'string',number:'number',integer:'number',boolean:'boolean',array:'array',object:'object',null:'null'};if(schema.type){const at=data===null?'null':Array.isArray(data)?'array':typeof data;if(!tm[schema.type]||at!==tm[schema.type]){errors.push(path+': 期望类型 '+schema.type+'，实际类型 '+at);return errors;}}if(schema.type==='string'&&schema.minLength!==undefined&&data.length<schema.minLength)errors.push(path+': 字符串长度不足');if(schema.type==='string'&&schema.maxLength!==undefined&&data.length>schema.maxLength)errors.push(path+': 字符串长度超出');if(schema.type==='string'&&schema.pattern&&!new RegExp(schema.pattern).test(data))errors.push(path+': 不符合 pattern');if((schema.type==='number'||schema.type==='integer')&&schema.minimum!==undefined&&data<schema.minimum)errors.push(path+': 小于最小值');if((schema.type==='number'||schema.type==='integer')&&schema.maximum!==undefined&&data>schema.maximum)errors.push(path+': 大于最大值');if(schema.type==='array'&&schema.items)data.forEach((item,idx)=>{errors.push(...v(item,schema.items,path+'['+idx+']'));});if(schema.type==='object'&&schema.properties){Object.entries(schema.properties).forEach(([k,s])=>{if(data[k]!==undefined)errors.push(...v(data[k],s,path?path+'.'+k:k));});if(schema.required)schema.required.forEach(k=>{if(!(k in data))errors.push(path+'.'+k+': 缺少必需字段');});}return errors;}function run(){try{const jt=ji.value.trim(),st=si.value.trim();if(!jt||!st){o.value='';return;}const data=JSON.parse(jt),schema=JSON.parse(st),errors=v(data,schema);if(!errors.length)o.value='OK - JSON 数据符合 Schema 定义';else o.value='验证失败 ('+errors.length+' 个错误)：\n\n'+errors.join('\n');}catch(e){o.value='Error: '+e.message;}}ji.addEventListener('input',run);si.addEventListener('input',run);document.getElementById('copyOutput').onclick=()=>copyToClipboard(o.value);'''
    ),

    # ---- 编码/加密工具 ----
    'encrypt/aes': (
        '''<div class="tool-card"><h3>输入</h3><textarea id="input" placeholder="输入文本..." style="min-height:80px;"></textarea><div style="margin-top:0.5rem;display:flex;gap:0.5rem;flex-wrap:wrap;align-items:center;"><label>密钥: <input type="text" id="keyInput" value="defaultpassword123456" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);width:150px;"></label><label>IV: <input type="text" id="ivInput" value="randomiv123456789" style="padding:0.4rem;border-radius:8px;border:1px solid var(--border);width:120px;"></label></div></div><div class="output-box"><h3>输出 <button class="copy-btn" id="copyOutput">复制</button></h3><textarea id="output" readonly style="min-height:80px;"></textarea><div class="btn-row" style="margin-top:0.5rem;"><button class="btn btn-primary" id="encryptBtn">🔐 加密</button><button class="btn btn-secondary" id="decryptBtn">